### ISSUE TITLE
[enhancement]: hardware minimums document

### ISSUE THREAD

**Issue by draconicfae** [invoke-ai/InvokeAI#2439]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

I would love to see documentation for invokeai detailing hardware minimums for the models it supports.  I have an RTX 3060 which has three times the ram (12GB) compared to the minimum specified in the invokeai readme (4GB), but I still get a cuda out of memory error for the 2.1-768 model.  Initially I thought it might be an invokeai bug, but all the other models run fine.  So now I think that it's telling the truth, and that my card really ISN'T good enough for the 768 generations.  

A potentially useful bit of additional information is that I'm not doing inpainting or img2img or other stuff where it could be having a problem because I'm trying to give it an image that's too big -- it gets this problem when I'm trying to do pure prompt based generation.

### Alternatives

I guess one alternative would be to continue to use the single hardware minimum specification in the main readme but drop support for models that require more than that (or increase the minimum to match whichever model is the hungriest, but that has the downside of losing a bunch of potential users who don't have good enough hardware for the hungriest model).

**Comment by mickr777** [comment]
Strange I have the 3060 12gb too but cant replicate cuda out of memory error on any output size with 2.1 768 even on 2048x2048.

I tried 960x1280 with hires fix, used 71% vram and takes about 30sec on 40 steps to make the output.

**Comment by codsec** [comment]
> Strange I have the 3060 12gb too but cant replicate cuda out of memory error on any output size with 2.1 768 even on 2048x2048.
> 
> I tried 960x1280 with hires fix, used 71% vram and takes about 25sec on 40 steps to make the output.
> 
> Honestly there is so many models out there that give better outputs then sd 2.1 I rarely use it.
> 
> Edit: I did just remember I am using xformers so it might be making a difference.

what is xformes?

**Comment by mickr777** [comment]
> what is xformes?
It give better performance and less memory usage on cuda based gpus,

Install instructions here
https://github.com/invoke-ai/InvokeAI/blob/main/docs/installation/070_INSTALL_XFORMERS.md

**Comment by draconicfae** [comment]
> > what is xformes?
> 
> It give better performance and less memory usage on cuda based gpus
> 
> follow the pip Install instructions here if you wish to try it out https://invoke-ai.github.io/InvokeAI/installation/070_INSTALL_XFORMERS/?h=xformers

I followed the steps and it works now, thanks!  In another comment you mentioned that sd 2.1 isn't generally your choice.  What would you recommend as a better model or models?  Or do you use fine tuned stuff which would mean the answer is "depends on what you're trying to make"?

**Comment by mickr777** [comment]
> I followed the steps and it works now, thanks! In another comment you mentioned that sd 2.1 isn't generally your choice. What would you recommend as a better model or models? Or do you use fine tuned stuff which would mean the answer is "depends on what you're trying to make"?

Yes it is a depends on what you want from it situation

At the moment I have been trying out the Protogen models https://huggingface.co/darkstorm2150/

I am Finding I am getting the results want from the Protogen Eclipse model (https://huggingface.co/darkstorm2150/Protogen_Eclipse_Official_Release)
![image](https://user-images.githubusercontent.com/115216705/215227426-5b11624d-318f-44c3-937e-a5a14d4b8ec9.png)

vs SD 2.1 768
![image](https://user-images.githubusercontent.com/115216705/215227598-4de13c9b-a619-4409-8cd2-95c21319a1fd.png)

same seed/steps/prompt at 768x768
