### ISSUE TITLE
[bug]: CUDA error: the launch timed out and was terminated (low VRAM)

### ISSUE THREAD

**Issue by AndreyDonchev** [invoke-ai/InvokeAI#2695]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

4GB

### What happened?

I installed the latest version and yesterday it was running, although with problems due to my low VRAM. Today I can't convince it to work. No matter what I try I receive a CUDA error.

### Screenshots

>> Image Generation Parameters:

{'prompt': 'Woman', 'iterations': 1, 'steps': 50, 'cfg_scale': 7.5, 'threshold': 0, 'perlin': 0, 'height': 1024, 'width': 768, 'sampler_name': 'k_euler', 'seed': 1080312913, 'progress_images': False, 'progress_latents': True, 'save_intermediates': 5, 'generation_mode': 'txt2img', 'init_mask': '...', 'seamless': False, 'hires_fix': False, 'variation_amount': 0}

>> ESRGAN Parameters: False
>> Facetool Parameters: False
>> Setting Sampler to k_euler (EulerDiscreteScheduler)
  0%|                                                                                           | 0/50 [00:03<?, ?it/s]
Generating:   0%|                                                                                | 0/1 [00:03<?, ?it/s]

Traceback (most recent call last):
  File "C:\Users\Me\invokeai\.venv\lib\site-packages\ldm\generate.py", line 516, in prompt2image
    results = generator.generate(
  File "C:\Users\Me\invokeai\.venv\lib\site-packages\ldm\invoke\generator\base.py", line 112, in generate
    image = make_image(x_T)
  File "C:\Users\Me\invokeai\.venv\lib\site-packages\ldm\invoke\generator\txt2img.py", line 40, in make_image
    pipeline_output = pipeline.image_from_embeddings(
  File "C:\Users\Me\invokeai\.venv\lib\site-packages\ldm\invoke\generator\diffusers_pipeline.py", line 340, in image_from_embeddings
    result_latents, result_attention_map_saver = self.latents_from_embeddings(
  File "C:\Users\Me\invokeai\.venv\lib\site-packages\ldm\invoke\generator\diffusers_pipeline.py", line 366, in latents_from_embeddings
    result: PipelineIntermediateState = infer_latents_from_embeddings(
  File "C:\Users\Me\invokeai\.venv\lib\site-packages\ldm\invoke\generator\diffusers_pipeline.py", line 181, in __call__
    for result in self.generator_method(*args, **kwargs):
  File "C:\Users\Me\invokeai\.venv\lib\site-packages\ldm\invoke\generator\diffusers_pipeline.py", line 401, in generate_latents_from_embeddings
    step_output = self.step(batched_t, latents, conditioning_data,
  File "C:\Users\Me\invokeai\.venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Me\invokeai\.venv\lib\site-packages\ldm\invoke\generator\diffusers_pipeline.py", line 446, in step
    step_output = self.scheduler.step(noise_pred, timestep, latents,
  File "C:\Users\Me\invokeai\.venv\lib\site-packages\diffusers\schedulers\scheduling_euler_discrete.py", line 217, in step
    step_index = (self.timesteps == timestep).nonzero().item()
RuntimeError: CUDA error: the launch timed out and was terminated
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Me\invokeai\.venv\lib\site-packages\invokeai\backend\invoke_ai_web_server.py", line 1204, in generate_images
    self.generate.prompt2image(
  File "C:\Users\Me\invokeai\.venv\lib\site-packages\ldm\generate.py", line 579, in prompt2image
    self.clear_cuda_cache()
  File "C:\Users\Me\invokeai\.venv\lib\site-packages\ldm\generate.py", line 607, in clear_cuda_cache
    torch.cuda.empty_cache()
  File "C:\Users\Me\invokeai\.venv\lib\site-packages\torch\cuda\memory.py", line 125, in empty_cache
    torch._C._cuda_emptyCache()
RuntimeError: CUDA error: the launch timed out and was terminated
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Me\invokeai\.venv\lib\site-packages\invokeai\backend\invoke_ai_web_server.py", line 633, in handle_generate_image_event
    self.generate_images(
  File "C:\Users\Me\invokeai\.venv\lib\site-packages\invokeai\backend\invoke_ai_web_server.py", line 1222, in generate_images
    self.empty_cuda_cache()
  File "C:\Users\Me\invokeai\.venv\lib\site-packages\invokeai\backend\invoke_ai_web_server.py", line 1234, in empty_cuda_cache
    torch.cuda.empty_cache()
  File "C:\Users\Me\invokeai\.venv\lib\site-packages\torch\cuda\memory.py", line 125, in empty_cache
    torch._C._cuda_emptyCache()
RuntimeError: CUDA error: the launch timed out and was terminated
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

### Contact Details

andrey.doncehv@gmail.com

**Comment by ebr** [comment]
```
'height': 1024, 'width': 768
```
I doubt you will be able to achieve this resolution with your GPU. Could you please try changing it to 512x512 and see if that helps?

**Comment by AndreyDonchev** [comment]
Thanks! I will!

**Comment by AndreyDonchev** [comment]
Yes, the problem is solved! Thank you!
