### ISSUE TITLE
[bug]: Running out of memory 2.3.1 RC3 - Free memory ON

### ISSUE THREAD

**Issue by telles0808** [invoke-ai/InvokeAI#2786]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

6GB

### What happened?

I was trying the weekly context on Discord and after +/-10 images I run out of memory. Changing Model empty the vRam, but doesn't solve the problem.
Also I have the Free vRam memory ON  in the settings.

### Screenshots

![image](https://user-images.githubusercontent.com/2066086/221070827-5cd4a080-3f4e-483d-ae75-f3c068dab57e.png)
![image](https://user-images.githubusercontent.com/2066086/221070848-5a7f4214-5eb8-48af-b4f8-2eba55a0af23.png)
![image](https://user-images.githubusercontent.com/2066086/221070868-9ae752e9-66ed-4b82-9877-2de6f5f1d4a9.png)
![image](https://user-images.githubusercontent.com/2066086/221070882-16b35b91-3f64-4109-b2a1-8dd304616c6a.png)

### Additional context

Using imgToimg and ddim

### Contact Details

telles.gabriel@gmail.com

**Comment by lstein** [comment]
@JPPhoto Could you have a look at this?

**Comment by telles0808** [comment]
I did a workaround. Every time it hit the max, I change something inside the model manager and update the model, purging it.

**Comment by lstein** [comment]
I'm working on this problem with @JPPhoto . Are you using the stock stable-diffusion-1.5 model, or something else?

**Comment by telles0808** [comment]
Standard sd1.5 diffuser

**Comment by JohnyTesla** [comment]
With higher resolution OOM appears sooner. Current VRAM usage after freeing keeps rising after every generation. It works fine (at least for me) when using safetensor model (VRAM usage after freeing is the same). Using Dreamshaper 3.31 safetensor model.

**Comment by telles0808** [comment]
Here even safetensor model increase memory, but due to the smaller size, it increase less. I tested using a 2GB safetensor model and it increased by 500mb each step

**Comment by lstein** [comment]
I think that through the efforts of @jpphoto we have fixed the memory
consumption issues. Could you please try with the 2.3.1 release and let me
know if the problem has improved (and hopefully disappeared).

Lincoln

**Comment by telles0808** [comment]
Solved

**Comment by JPPhoto** [comment]
Most excellent! I am closing this issue in that case.
