### ISSUE TITLE
[bug]: CUDA out of memory error with 3.1.1. No previous issue with 3.1.0.

### ISSUE THREAD

**Issue by JakeSSRN** [invoke-ai/InvokeAI#4573]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

8 GB

### What version did you experience this issue on?

3.1.1

### What happened?

I'm getting the typical 'CUDA out of memory' error when generating with SDXL and SD2.1. With SD2.1 I even generate at 512x512 and 1 image batch size. In 3.1.0 I could generate a batch size of 3 at 1024x1024 with SDXL without running into problems. What gives?

System RAM cache is set to 12 of 16 GB and VRAM cache is set to 0 of 8 GB. 

I noticed that the "free GPU memory after every generation" option is gone. I suspect this has something to do with it. Also, the whole browser crashes as soon as the error is thrown and I have to restart both the browser and Invoke to get it working again.

I've posted in the help section of the discord two days in a row now with absolutely zero response. I'd appreciate some insight, please.

### Screenshots

<img width="857" alt="Screenshot 2023-09-17 140202" src="https://github.com/invoke-ai/InvokeAI/assets/143065738/9ba656c1-4c25-4d6e-9a43-a90bbaf6c8cb">

### Additional context

Probably unrelated: how I do I get Invoke to stop opening an new tab with the asset images in it every time I generate with the unified canvas?

**Comment by Millu** [comment]
Sorry you message was missed on Discord - just responded there!

**Comment by schoenid** [comment]
Same to me ...

**Comment by Petterson19** [comment]
> Same to me ... except I'm on Ubuntu 22.04. Seems not to be a model problem. If I use the CPU only, it works, but it needs just 10+ times longer.

I found a solution, just downloaded CUDA from Nvidia and it's running smoothly now!

**Comment by JakeSSRN** [comment]
I uninstalled and reinstalled both CUDA toolkit and visual studio and restarted in between each step. No improvement.

**Comment by Petterson19** [comment]
> > I found a solution, just downloaded CUDA from Nvidia and it's running smoothly now!
> 
> I uninstalled and reinstalled both CUDA toolkit and Visual Studio and restarted in between each step. No improvement.

Why didn't you use phyton in prompt or PowerShell? just too easy to install it

**Comment by schoenid** [comment]
So I made a mistake. The selected model I thougt was SDXL was SD2.1 only.

On SDXL and CUDA enabled I've got always Memory Errors:
```
[2023-09-21 00:36:29,950]::[InvokeAI]::ERROR --> Error while invoking:
CUDA out of memory. Tried to allocate 26.00 MiB (GPU 0; 7.78 GiB total capacity; 5.80 GiB already allocated; 61.69 MiB free; 6.04 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

Hm, the message means: 61.69 MiB are free, but 26.00 MiB can't be allocated. (Why ???)
The PYTORCH_CUDA_ALLOC_CONF is a matter for the developer, as I see. I can't do this setting.

So SDXL is not usable on CUDA in invoke ai v3.1.1.

Remark
nvidia-smi:
```
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1443      G   /usr/lib/xorg/Xorg                284MiB |
|    0   N/A  N/A      2268      G   /usr/bin/kwin_x11                  66MiB |
|    0   N/A  N/A      2316      G   /usr/bin/plasmashell               94MiB |
|    0   N/A  N/A      2785      G   ...402625461174669194,262144      166MiB |
|    0   N/A  N/A     55892      C   ...keAI/.venv/bin/python3.10     7260MiB |
+-----------------------------------------------------------------------------+
```
First 3 is the system
4th is my browser (Opera / required for UI)
5th is invoke ai

**Comment by JakeSSRN** [comment]
I'm at a loss here. I guess I'll just have to wait for an update.

**Comment by JakeSSRN** [comment]
In a last ditch effort, I did a clean install of Windows 11. Invoke v3.1.1 now works. Still no idea what the issue was.

**Comment by schoenid** [comment]
I didn't realize, that the amount of used GPU memory (VRAM) can be reduced in setup:
![image](https://github.com/invoke-ai/InvokeAI/assets/15383666/07e76074-8717-4493-9bb3-8f4214a794c0)

So easy!
Now everything works fine!

**Comment by icamps** [comment]
Having this same error with InvokeAI 4.2.7.

No option in setup to reduce the amount of memory used, either option to  "free GPU memory after every generation".

My box is running Ubuntu 22.04 and CUDA 12.4.
