### ISSUE TITLE
[bug]: Get RuntimeError when using AMD gpu

### ISSUE THREAD

**Issue by genelatham** [invoke-ai/InvokeAI#5738]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Linux

### GPU vendor

AMD (ROCm)

### GPU model

AMD Radeon RX 6700 XT

### GPU VRAM

12GB

### Version number

3.7.0

### Browser

Brave

### Python dependencies

Local System
accelerate 0.27.2
compel 2.0.2
cuda Not Installed
diffusers 0.26.3
numpy 1.26.4
opencv 4.9.0.80
onnx 1.15.0
pillow 10.2.0
python 3.10.12
torch 2.1.2+rocm5.6
torchvision 0.16.2+rocm5.6
transformers 4.37.2
xformers Not Installed

### What happened

While attempting to generate an image the process aborts with:
**RuntimeError: HIP error: the operation cannot be performed in the present state**

I left all the settings at the out of the box setting. The model was sd-v1-5. The prompt was: "cat"

### What you expected to happen

To get a picture of a cat.

### How to reproduce the problem

I am using ROCm version 6.0.0. Here is a trace of an entire session:
[trace.txt](https://github.com/invoke-ai/InvokeAI/files/14319615/trace.txt)

**Comment by genelatham** [comment]
I resolved this with:
**pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/rocm6.0**
