### ISSUE TITLE
[bug]: Insufficient GPU memory to load model. Aborting on 12 Gb VRAM system

### ISSUE THREAD

**Issue by SuperBoss9** [invoke-ai/InvokeAI#6106]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Windows

### GPU vendor

Nvidia (CUDA)

### GPU model

RTX 2060

### GPU VRAM

12GB

### Version number

v4.0.0

### Browser

Yandex Browser

### Python dependencies

{
  "accelerate": "0.28.0",
  "compel": "2.0.2",
  "cuda": "12.1",
  "diffusers": "0.27.2",
  "numpy": "1.26.4",
  "opencv": "4.9.0.80",
  "onnx": "1.15.0",
  "pillow": "10.2.0",
  "python": "3.10.9",
  "torch": "2.2.1+cu121",
  "torchvision": "0.17.1+cu121",
  "transformers": "4.39.1",
  "xformers": "0.0.25"
}

### What happened

`[2024-04-02 22:35:41,214]::[ModelManagerService]::WARNING --> Insufficient GPU memory to load model. Aborting
[2024-04-02 22:35:41,216]::[InvokeAI]::ERROR --> Error while invoking session a2efc518-d2d3-4375-b492-821cb6b74ae5, invocation be45bf0e-9a59-41b9-a2b9-81db91120b09 (denoise_latents):

[2024-04-02 22:35:41,216]::[InvokeAI]::ERROR --> Traceback (most recent call last):
  File "Z:\InvokeAI\.venv\lib\site-packages\invokeai\app\services\session_processor\session_processor_default.py", line 179, in _process
    outputs = self._invocation.invoke_internal(
  File "Z:\InvokeAI\.venv\lib\site-packages\invokeai\app\invocations\baseinvocation.py", line 281, in invoke_internal
    output = self.invoke(context)
  File "Z:\InvokeAI\.venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "Z:\InvokeAI\.venv\lib\site-packages\invokeai\app\invocations\latent.py", line 772, in invoke
    ip_adapter_data = self.prep_ip_adapter_data(
  File "Z:\InvokeAI\.venv\lib\site-packages\invokeai\app\invocations\latent.py", line 533, in prep_ip_adapter_data
    with image_encoder_model_info as image_encoder_model:
  File "Z:\InvokeAI\.venv\lib\site-packages\invokeai\backend\model_manager\load\load_base.py", line 31, in __enter__
    self._locker.lock()
  File "Z:\InvokeAI\.venv\lib\site-packages\invokeai\backend\model_manager\load\model_cache\model_locker.py", line 42, in lock
    self._cache.move_model_to_device(self._cache_entry, self._cache.execution_device)
  File "Z:\InvokeAI\.venv\lib\site-packages\invokeai\backend\model_manager\load\model_cache\model_cache_default.py", line 273, in move_model_to_device
    self._check_free_vram(target_device, cache_entry.size)
  File "Z:\InvokeAI\.venv\lib\site-packages\invokeai\backend\model_manager\load\model_cache\model_cache_default.py", line 432, in _check_free_vram
    raise torch.cuda.OutOfMemoryError
torch.cuda.OutOfMemoryError

[2024-04-02 22:35:41,217]::[InvokeAI]::INFO --> Graph stats: a2efc518-d2d3-4375-b492-821cb6b74ae5
                          Node   Calls   Seconds  VRAM Used
             sdxl_model_loader       1    0.000s     0.000G
            sdxl_compel_prompt       2    2.513s     1.545G
                         noise       1    0.012s     1.538G
                 core_metadata       1    0.000s     1.538G
                    controlnet       1    0.001s     1.538G
                       collect       2    0.000s     1.538G
                    ip_adapter       1    0.000s     1.538G
               denoise_latents       1   10.898s     9.464G
TOTAL GRAPH EXECUTION TIME:  13.424s
TOTAL GRAPH WALL TIME:  13.429s
RAM used by InvokeAI process: 6.48G (+5.831G)
RAM used to load models: 13.60G
VRAM in use: 7.923G
RAM cache statistics:
   Model cache hits: 13
   Model cache misses: 9
   Models cached: 9
   Models cleared from cache: 0
   Cache high water mark: 12.07/24.00G`

Happens during attempt of generation of an image with 'ip_adapter_sdxl' and 'controlnet-sd-xl-1.0-softedge-dexined'. Regardless to used model, steps etc.

The same render config was used at the same machine with 3.7.1 and it works fine. Similar config at the same machine works fine under Fooocus.

I was tried to modify invokeai.yaml to the following with no success:
`ram: 24
vram: 11
lazy_offload: true
`

What can be wrong?

### What you expected to happen

A picture generated

### How to reproduce the problem

Use IPAdapter with ControlNet SoftEdge with SDXL

**Comment by psychedelicious** [comment]
We expect it to fail with `vram` set to 11GB on a 12GB card. `vram` dictates how much space should be allocated for the VRAM cache of model weights. Whatever is left over is available for inference. In this case, that leaves only 1GB for inference, which is definitely not enough.

Suggest removing the `vram` setting entirely, let us manage it - did you already try that?

**Comment by SuperBoss9** [comment]
> Suggest removing the vram setting entirely, let us manage it - did you already try that?

Yes, initially the yaml file was without VRAM directive. So I've added it hoping that that can solve the problem. Not helped.

**Comment by psychedelicious** [comment]
Ok, thanks for confirming.

@lstein, we've had a number of reports of OOMs on v4 that did not occur on v3.7. Enough reports to suggest that VRAM usage has changed substantially since v3.7. Can you please investigate?

**Comment by lstein** [comment]
I have attempted to reproduce the problem using an SDXL model, `ip_adapter_sdxl`, and `controlnet-sd-xl-1.0-softedge-dexined`. Sure enough it runs out of memory on 4.0.2, but it also runs out of memory on 3.7.

Do you happen to have a working copy of 3.7 still around, and if so could you tell me what versions of the dependencies you have? I'd like to check this to see if it may be a problem upstream (e.g. with diffusers).

**Comment by SuperBoss9** [comment]
> Which model were you using?

![image](https://github.com/invoke-ai/InvokeAI/assets/53711021/2226d853-660c-4fca-a84c-494000b188ac)

But the problem appears also with other models.

![image](https://github.com/invoke-ai/InvokeAI/assets/53711021/9ceb9f7e-b64b-43fb-8ac3-0076428d4d01)

The adapters are here.

That works for sure with 3.7. And it works with Fooocus with the same models and adapters (actually they are not the same but do the same work).

**Comment by psychedelicious** [comment]
@SuperBoss9 Thank you.

I did some testing on a windows machine with an RTX 4070 TI w/ 12GB VRAM (like your 2060). I was able to reproduce the issue using the same models.

---

Some background:

There was a problem in v3 where if we ran out of VRAM, sometimes we couldn't reclaim the VRAM allocated to the models. This caused a VRAM memory leak. Unfortunately, this behaviour seems to be inherent to `torch`.

To mitigate this, v4 does an additional check before loading a model. The check ask `torch` how much memory is available before loading the model. If there isn't enough, it raises the error you are getting.

This works as expected on Linux, but not on Windows 10/11. When a process on Windows requests more VRAM than is available on the GPU, Windows is able to allocate some of the system's RAM - up to 50% by default, apparently. You can see how much RAM is used for this in the Task Manager's GPU section with label `Shared GPU memory usage`.

Here's an nvidia support article describing how to opt-out of this behaviour: https://nvidia.custhelp.com/app/answers/detail/a_id/5490

When we ask `torch` how much memory is available, it only reports the GPU VRAM. It does not report much RAM is available to it - this is managed by Windows at a higher level. The result is that torch under-represents the amount of memory available to the GPU.

---

Back to my testing. I disabled the extra VRAM check and do not get an OOM error. GPU memory is at 100%, but Windows picks up the slack and an additional ~3GB RAM is used. The GPU is using 15GB of memory in total (on the 12GB card).

So the check we are doing to prevent the memory leak mistakenly thinks that we will get an OOM error if we try to load the model and bails out.

Two proposals:
1. Remove the VRAM check entirely. Fix the memory leak. Update docs and link to the nvidia support article, help users to select the correct python executable to.
    
    I think this is best, even if we don't fix the memory leak issue immediately. The existing behaviour is retained. We let the GPU driver handle the shared GPU memory stuff.

2. Add an invoke setting to opt-out (e.g. `allow_shared_gpu_memory: bool`). 
    
    Though this works around the memory leak, it puts the burden on us to carefully manage memory. Ideally, we don't need to do this.

I prefer option 1.

@lstein @RyanJDick @hipsterusername

**Comment by psychedelicious** [comment]
I've PR'd proposal 1 above. IMO, we should get this out ASAP to resolve user-facing issues.

**Comment by SuperBoss9** [comment]
Note:
After upgrade to 4.0.2 I can use IPAdapter and T2I Adapter with the rest settings and it doesn't lead to OutOfMemory error.
