### ISSUE TITLE
[bug]: ROCm Out of Memory Errors - Excessive VRAM Allocation

### ISSUE THREAD

**Issue by ThisNekoGuy** [invoke-ai/InvokeAI#6301]
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Linux

### GPU vendor

AMD (ROCm)

### GPU model

RX 7800 XT

### GPU VRAM

16GB

### Version number

4.2.0a4

### Browser

LibreWolf 125.0.2-1

### Python dependencies

```json
{
  "accelerate": "0.29.2",
  "compel": "2.0.2",
  "cuda": null,
  "diffusers": "0.27.2",
  "numpy": "1.26.4",
  "opencv": "4.9.0.80",
  "onnx": "1.15.0",
  "pillow": "10.3.0",
  "python": "3.11.9",
  "torch": "2.2.2+rocm5.6",
  "torchvision": "0.17.2+rocm5.6",
  "transformers": "4.39.3",
  "xformers": null
}
```

### What happened

When trying to generate an image, a huge amount of VRAM was allocated and prevented the image generation from being able to request any more to actually... generate the image.

Coming from Nvidia to AMD recently, of which my Nvidia card had only 11GBs, I find this unusual because I only tried making a 832x1480 image and that's not particularly large (at least, not large enough to trigger OOM on my Nvidia card when I used other Stable Diffusion front-ends before I came to InvokeAI today).

### What you expected to happen

I expected the image to be able to generate without issue; probably even with VRAM to spare.

### How to reproduce the problem

1. Edit the `invoke.sh` script to modify line 41 to `HSA_OVERRIDE_GFX_VERSION=11.0.0 invokeai-web $PARAMS` to get past an initial segfault bug when attempting generations
2. [Use this model](https://civitai.com/models/41916/koji)
3. [Use this VAE](https://huggingface.co/hakurei/waifu-diffusion-v1-4/blob/main/vae/kl-f8-anime.ckpt)
4. Set aspect ratio to `9:16`
5. Set width to `832`
6. Set height to `1480`
7. Enable High Resolution Fix (or don't, it doesn't matter, result is the same)
8. If you enabled the High Resolution Fix, set denoise to `0.55` and set the upscaler to `ESRGAN`
9. Set the scheduler to `DPM ++2M Karras`
10. Set steps to `25`
11. Set CFG Scale to `7.5`
12. Leave the VAE at the default precision (`FP32`)
13. Set Click Skip to `2`
14. Leave CFG Rescale Multiplier at `0` or follow the tooltip and set it to `0.7` (Result is the same, regardless)

### Additional context

Specific Linux Distro: Gentoo (LLVM17 Built)
[Blas Implementation](https://wiki.gentoo.org/wiki/Blas-lapack-switch#Recommendations): openblas

<details><summary>Terminal Output:</summary>

```
Generate images with a browser-based interface
>> patchmatch.patch_match: ERROR - patchmatch failed to load or compile (/usr/lib64/libtiff.so.6: undefined symbol: jpeg12_read_raw_data, version LIBJPEG_6.2).
>> patchmatch.patch_match: INFO - Refer to https://invoke-ai.github.io/InvokeAI/installation/060_INSTALL_PATCHMATCH/ for installation instructions.
[2024-05-02 07:37:46,993]::[InvokeAI]::INFO --> Patchmatch not loaded (nonfatal)
[2024-05-02 07:38:06,846]::[InvokeAI]::INFO --> Using torch device: AMD Radeon RX 7800 XT
[2024-05-02 07:38:07,024]::[InvokeAI]::INFO --> cuDNN version: 2020000
[2024-05-02 07:38:07,038]::[uvicorn.error]::INFO --> Started server process [19373]
[2024-05-02 07:38:07,038]::[uvicorn.error]::INFO --> Waiting for application startup.
[2024-05-02 07:38:07,038]::[InvokeAI]::INFO --> InvokeAI version 4.2.0a4
[2024-05-02 07:38:07,039]::[InvokeAI]::INFO --> Root directory = /mnt/chonker/InvokeAI/InstallDir
[2024-05-02 07:38:07,039]::[InvokeAI]::INFO --> Initializing database at /mnt/chonker/InvokeAI/InstallDir/databases/invokeai.db
[2024-05-02 07:38:07,277]::[InvokeAI]::INFO --> Pruned 1 finished queue items
[2024-05-02 07:38:07,752]::[InvokeAI]::INFO --> Cleaned database (freed 0.02MB)
[2024-05-02 07:38:07,752]::[uvicorn.error]::INFO --> Application startup complete.
[2024-05-02 07:38:07,752]::[uvicorn.error]::INFO --> Uvicorn running on http://127.0.0.1:9090 (Press CTRL+C to quit)
[2024-05-02 07:38:09,825]::[uvicorn.access]::INFO --> 127.0.0.1:58476 - "GET /ws/socket.io/?EIO=4&transport=polling&t=OyvJ-gP HTTP/1.1" 200
[2024-05-02 07:38:09,830]::[uvicorn.access]::INFO --> 127.0.0.1:58476 - "POST /ws/socket.io/?EIO=4&transport=polling&t=OyvJ-gf&sid=REhucWSM_N8uuUmfAAAA HTTP/1.1" 200
[2024-05-02 07:38:09,831]::[uvicorn.error]::INFO --> ('127.0.0.1', 58488) - "WebSocket /ws/socket.io/?EIO=4&transport=websocket&sid=REhucWSM_N8uuUmfAAAA" [accepted]
[2024-05-02 07:38:09,832]::[uvicorn.error]::INFO --> connection open
[2024-05-02 07:38:09,832]::[uvicorn.access]::INFO --> 127.0.0.1:58494 - "GET /ws/socket.io/?EIO=4&transport=polling&t=OyvJ-gf.0&sid=REhucWSM_N8uuUmfAAAA HTTP/1.1" 200
[2024-05-02 07:38:09,836]::[uvicorn.access]::INFO --> 127.0.0.1:58476 - "GET /ws/socket.io/?EIO=4&transport=polling&t=OyvJ-gf.1&sid=REhucWSM_N8uuUmfAAAA HTTP/1.1" 200
[2024-05-02 07:38:09,864]::[uvicorn.access]::INFO --> 127.0.0.1:58476 - "GET /api/v1/queue/default/status HTTP/1.1" 200
[2024-05-02 07:38:10,080]::[uvicorn.access]::INFO --> 127.0.0.1:58476 - "GET /api/v1/images/?board_id=none&categories=control&categories=mask&categories=user&categories=other&is_intermediate=false&limit=0&offset=0 HTTP/1.1" 200
[2024-05-02 07:38:10,081]::[uvicorn.access]::INFO --> 127.0.0.1:58494 - "GET /api/v1/app/config HTTP/1.1" 200
[2024-05-02 07:38:10,082]::[uvicorn.access]::INFO --> 127.0.0.1:58476 - "GET /api/v1/images/?board_id=none&categories=general&is_intermediate=false&limit=0&offset=0 HTTP/1.1" 200
[2024-05-02 07:38:10,082]::[uvicorn.access]::INFO --> 127.0.0.1:58494 - "GET /api/v1/images/intermediates HTTP/1.1" 200
[2024-05-02 07:38:10,083]::[uvicorn.access]::INFO --> 127.0.0.1:58506 - "GET /api/v1/app/version HTTP/1.1" 200
[2024-05-02 07:38:10,083]::[uvicorn.access]::INFO --> 127.0.0.1:58510 - "GET /api/v1/boards/?all=true HTTP/1.1" 200
[2024-05-02 07:38:10,084]::[uvicorn.access]::INFO --> 127.0.0.1:58524 - "GET /api/v1/images/?board_id=none&categories=general&is_intermediate=false&limit=100&offset=0 HTTP/1.1" 200
[2024-05-02 07:38:10,093]::[uvicorn.access]::INFO --> 127.0.0.1:58536 - "GET /api/v1/app/app_deps HTTP/1.1" 200
[2024-05-02 07:38:10,094]::[uvicorn.access]::INFO --> 127.0.0.1:58476 - "GET /api/v1/queue/default/list HTTP/1.1" 200
[2024-05-02 07:38:10,095]::[uvicorn.access]::INFO --> 127.0.0.1:58494 - "GET /api/v1/queue/default/status HTTP/1.1" 200
[2024-05-02 07:38:19,190]::[uvicorn.access]::INFO --> 127.0.0.1:40554 - "POST /api/v1/queue/default/enqueue_batch HTTP/1.1" 200
[2024-05-02 07:38:19,410]::[uvicorn.access]::INFO --> 127.0.0.1:40554 - "GET /api/v1/queue/default/status HTTP/1.1" 200
[2024-05-02 07:38:19,444]::[uvicorn.access]::INFO --> 127.0.0.1:40568 - "GET /api/v1/queue/default/list HTTP/1.1" 200
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 25/25 [00:09<00:00,  2.57it/s]
/mnt/chonker/InvokeAI/InstallDir/.venv/lib/python3.11/site-packages/lightning_utilities/core/imports.py:14: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
/mnt/chonker/InvokeAI/InstallDir/.venv/lib/python3.11/site-packages/pkg_resources/__init__.py:2832: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/mnt/chonker/InvokeAI/InstallDir/.venv/lib/python3.11/site-packages/lightning_fabric/__init__.py:40: Deprecated call to `pkg_resources.declare_namespace('lightning_fabric')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
/mnt/chonker/InvokeAI/InstallDir/.venv/lib/python3.11/site-packages/pytorch_lightning/__init__.py:37: Deprecated call to `pkg_resources.declare_namespace('pytorch_lightning')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
[2024-05-02 07:38:52,148]::[ModelLoadService]::INFO --> Converting /mnt/chonker/InvokeAI/InstallDir/models/sd-1/vae/kl-f8-anime2.ckpt to diffusers format
[2024-05-02 07:39:05,988]::[uvicorn.access]::INFO --> 127.0.0.1:33102 - "GET /api/v1/images/i/b38fe7ca-e4a0-404c-ba73-6a5f59acd186.png HTTP/1.1" 200
[2024-05-02 07:39:06,196]::[InvokeAI]::INFO --> Downloading RealESRGAN_x4plus.pth...
RealESRGAN_x4plus.pth: 67.1MiB [01:12, 929kiB/s]                                                                                                                                                                     
Upscaling: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:12<00:00,  6.08s/it]
[2024-05-02 07:40:32,518]::[uvicorn.access]::INFO --> 127.0.0.1:37426 - "GET /api/v1/images/i/f9bc272e-5d2e-4db7-91b6-618951310362.png HTTP/1.1" 200
[2024-05-02 07:40:32,728]::[uvicorn.access]::INFO --> 127.0.0.1:37426 - "GET /api/v1/images/i/08b0fd84-8637-4d7c-981b-db15358bc173.png HTTP/1.1" 200
  0%|                                                                                                                                                                                         | 0/14 [00:03<?, ?it/s]
[2024-05-02 07:40:52,353]::[InvokeAI]::ERROR --> Error while invoking session f0d54825-89e2-4f9f-8acb-4e24b2f43737, invocation 18dd1847-bf84-4d6b-9269-f76177444e74 (denoise_latents):
HIP out of memory. Tried to allocate 11.03 GiB. GPU 0 has a total capacity of 15.98 GiB of which 2.48 GiB is free. Of the allocated memory 12.84 GiB is allocated by PyTorch, and 48.98 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_HIP_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
[2024-05-02 07:40:52,353]::[InvokeAI]::ERROR --> Traceback (most recent call last):
  File "/mnt/chonker/InvokeAI/InstallDir/.venv/lib/python3.11/site-packages/invokeai/app/services/session_processor/session_processor_default.py", line 185, in _process
    outputs = self._invocation.invoke_internal(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/chonker/InvokeAI/InstallDir/.venv/lib/python3.11/site-packages/invokeai/app/invocations/baseinvocation.py", line 281, in invoke_internal
    output = self.invoke(context)
             ^^^^^^^^^^^^^^^^^^^^
  File "/mnt/chonker/InvokeAI/InstallDir/.venv/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/chonker/InvokeAI/InstallDir/.venv/lib/python3.11/site-packages/invokeai/app/invocations/latent.py", line 991, in invoke
    result_latents = pipeline.latents_from_embeddings(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/chonker/InvokeAI/InstallDir/.venv/lib/python3.11/site-packages/invokeai/backend/stable_diffusion/diffusers_pipeline.py", line 339, in latents_from_embeddings
    latents = self.generate_latents_from_embeddings(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/chonker/InvokeAI/InstallDir/.venv/lib/python3.11/site-packages/invokeai/backend/stable_diffusion/diffusers_pipeline.py", line 419, in generate_latents_from_embeddings
    step_output = self.step(
                  ^^^^^^^^^^
  File "/mnt/chonker/InvokeAI/InstallDir/.venv/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/chonker/InvokeAI/InstallDir/.venv/lib/python3.11/site-packages/invokeai/backend/stable_diffusion/diffusers_pipeline.py", line 517, in step
    uc_noise_pred, c_noise_pred = self.invokeai_diffuser.do_unet_step(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/chonker/InvokeAI/InstallDir/.venv/lib/python3.11/site-packages/invokeai/backend/stable_diffusion/diffusion/shared_invokeai_diffusion.py", line 199, in do_unet_step
    ) = self._apply_standard_conditioning(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/chonker/InvokeAI/InstallDir/.venv/lib/python3.11/site-packages/invokeai/backend/stable_diffusion/diffusion/shared_invokeai_diffusion.py", line 343, in _apply_standard_conditioning
    both_results = self.model_forward_callback(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/chonker/InvokeAI/InstallDir/.venv/lib/python3.11/site-packages/invokeai/backend/stable_diffusion/diffusers_pipeline.py", line 590, in _unet_forward
    return self.unet(
           ^^^^^^^^^^
  File "/mnt/chonker/InvokeAI/InstallDir/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/chonker/InvokeAI/InstallDir/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/chonker/InvokeAI/InstallDir/.venv/lib/python3.11/site-packages/diffusers/models/unets/unet_2d_condition.py", line 1216, in forward
    sample, res_samples = downsample_block(
                          ^^^^^^^^^^^^^^^^^
  File "/mnt/chonker/InvokeAI/InstallDir/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/chonker/InvokeAI/InstallDir/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/chonker/InvokeAI/InstallDir/.venv/lib/python3.11/site-packages/diffusers/models/unets/unet_2d_blocks.py", line 1279, in forward
    hidden_states = attn(
                    ^^^^^
  File "/mnt/chonker/InvokeAI/InstallDir/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/chonker/InvokeAI/InstallDir/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/chonker/InvokeAI/InstallDir/.venv/lib/python3.11/site-packages/diffusers/models/transformers/transformer_2d.py", line 397, in forward
    hidden_states = block(
                    ^^^^^^
  File "/mnt/chonker/InvokeAI/InstallDir/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/chonker/InvokeAI/InstallDir/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/chonker/InvokeAI/InstallDir/.venv/lib/python3.11/site-packages/diffusers/models/attention.py", line 329, in forward
    attn_output = self.attn1(
                  ^^^^^^^^^^^
  File "/mnt/chonker/InvokeAI/InstallDir/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/chonker/InvokeAI/InstallDir/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/chonker/InvokeAI/InstallDir/.venv/lib/python3.11/site-packages/diffusers/models/attention_processor.py", line 522, in forward
    return self.processor(
           ^^^^^^^^^^^^^^^
  File "/mnt/chonker/InvokeAI/InstallDir/.venv/lib/python3.11/site-packages/diffusers/models/attention_processor.py", line 1279, in __call__
    hidden_states = F.scaled_dot_product_attention(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch.cuda.OutOfMemoryError: HIP out of memory. Tried to allocate 11.03 GiB. GPU 0 has a total capacity of 15.98 GiB of which 2.48 GiB is free. Of the allocated memory 12.84 GiB is allocated by PyTorch, and 48.98 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_HIP_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

[2024-05-02 07:40:52,354]::[InvokeAI]::INFO --> Graph stats: f0d54825-89e2-4f9f-8acb-4e24b2f43737
                          Node   Calls   Seconds  VRAM Used
             main_model_loader       1    0.001s     0.000G
                     clip_skip       1    0.000s     0.000G
                        compel       2    5.175s     0.343G
                       collect       2    0.000s     0.236G
                         noise       2    0.004s     0.294G
               denoise_latents       2   27.174s    12.907G
                 core_metadata       1    0.000s     1.615G
                    vae_loader       1    0.000s     1.615G
                           l2i       1   18.170s     3.224G
                        esrgan       1   86.134s     7.383G
                    img_resize       1    0.535s     0.294G
                           i2l       1   15.543s     3.693G
TOTAL GRAPH EXECUTION TIME: 152.736s
TOTAL GRAPH WALL TIME: 152.744s
RAM used by InvokeAI process: 3.69G (+2.874G)
RAM used to load models: 3.97G
VRAM in use: 1.615G
RAM cache statistics:
   Model cache hits: 10
   Model cache misses: 5
   Models cached: 5
   Models cleared from cache: 0
   Cache high water mark: 1.99/7.50G
```
</details>

**Comment by psychedelicious** [comment]
That is super excessive VRAM usage. Looks like it is running really, really slowly too. The ESRGAN upscale is ridiculously slow. 

Unfortunately, I don't have an AMD GPU to test on. Not sure if any regular contributors do. May need community help to figure this out...

From a brief search, it looks like the env var `PYTORCH_HIP_ALLOC_CONF` may be useful. This old post for A1111 has a value to try: https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/6460#issuecomment-1382623085

If fp32 is being used instead of fp16, you'll use ~2x VRAM - try setting `precision: float16` in `invokeai.yaml`.

**Comment by ThisNekoGuy** [comment]
Setting both `PYTORCH_HIP_ALLOC_CONF=garbage_collection_threshold:0.9,max_split_size_mb:512` and `precision: float 16` doesn't seem to fix it. :v
(But then again, I noticed that adding `log_format: color` didn't actually add colored output either, so maybe the yaml just isn't being read? I'm loading the environment variables directly via the script though, so I know that's at least being read)
This is weird.

**Comment by psychedelicious** [comment]
If you suspect the YAML file isn't being read, an easy way to test is add `use_memory_db: true`. You should see a line like this on startup:
```
[2024-05-03 13:30:13,686]::[InvokeAI]::INFO --> Initializing in-memory database
```

Sorry, I'm not sure where to go from here with the performance issue :/

**Comment by ThisNekoGuy** [comment]
Ah, that does appear in the terminal output; so I guess it is reading the file but just... not outputting color for some reason? I guess that would otherwise be somewhat reasonably safe to assume that `precision: float 16` is being passed but whatever the root problem is simply doesn't care.

**Comment by psychedelicious** [comment]
We expect colored logs for warnings and errors only (and debug, if you set the log level accordingly). This works for me.

I'm confident the precision is set correctly in normal circumstances, but who knows with the issues you are facing.

**Comment by mcgravier** [comment]
So there are few things I observed with this

Tests are done with 1024x768 image generation with SD1.5 models. SDXL doesn't seem to suffer from the issue. 

All vram usage values were noted with Corectrl software - so it's total system Vram usage, not just what Invoke reports. I use 7900XTX 24GB

1. Set vram: 0 in the yaml config file. Setting it even to a small value like 0.5 causes multiple gigs of vram to be wasted
2. Set attention_type: sliced and attention_slice_size: max - for some reason this reduces vram usage by a LOT compared to other options. You can squeeze 1472x1472 image into 12GB with this. BUT it doesn't help at all when IP-Adapters and Controlnets are involved
3. Set sequential_guidance: true - this shaves off additional few gigs of vram in all cases

The worst case scenario in my case is when I use upscaling node on 1024x768 image (scale factor 2). Without aforementioned settings it sometimes fails to process on 24GB GPU! With theses settings it completes with ~15GB of peak Vram usage

**Comment by darksylinc** [comment]
Trying to generate an SD1.5 of 1024x1024 always runs OoM instantly.


`PYTORCH_HIP_ALLOC_CONF=garbage_collection_threshold:0.9,max_split_size_mb:512` helps a lot with SDXL and ControlNets, but the problem doesn't go away entirely. And for SD1.5, generating 1024x1024 appears to be impossible.

## Specs:
AMD Ryzen 5900X
RAM: 32GB
AMD Radeon HD 6800 XT 16GB
ROCm 6.4.1

## invokeai.yaml

```yaml
# Internal metadata - do not edit:
schema_version: 4.0.2

# Put user settings here - see https://invoke-ai.github.io/InvokeAI/configuration/:
enable_partial_loading: true
# precision: float16
device_working_mem_gb: 4
```

# 16G sounds suspicious

This report is very SUS: It says it's trying to allocate 16GB when generating 1024x1024 with SD1.5 and that obviously fails.

**Is it possible that the CUDA backend is doing the same thing but CUDA manages to gracefully handle unpaged memory?**

I noticed ROCm does paging VRAM at all (aka fallback to RAM); so trying to allocate 16GB in CUDA can succeed as long as all of that 16GB is not used all at once at the same time. Meanwhile ROCm fails spectacularly.

```
PYTORCH_HIP_ALLOC_CONF=garbage_collection_threshold:0.9,max_split_size_mb:512 "/home/matias/AI/invokeai/Invoke Community Edition.AppImage"
Starting up...

Started Invoke process with PID: 28883

bitsandbytes library load error: Configured CUDA binary not found at /home/matias/AI/invokeai/.venv/lib/python3.12/site-packages/bitsandbytes/libbitsandbytes_rocm63.so
Traceback (most recent call last):
  File "/home/matias/AI/invokeai/.venv/lib/python3.12/site-packages/bitsandbytes/cextension.py", line 290, in <module>
    lib = get_native_library()
          ^^^^^^^^^^^^^^^^^^^^
  File "/home/matias/AI/invokeai/.venv/lib/python3.12/site-packages/bitsandbytes/cextension.py", line 270, in get_native_library
    raise RuntimeError(f"Configured CUDA binary not found at {cuda_binary_path}")
RuntimeError: Configured CUDA binary not found at /home/matias/AI/invokeai/.venv/lib/python3.12/site-packages/bitsandbytes/libbitsandbytes_rocm63.so

[2025-06-27 15:00:13,518]::[InvokeAI]::INFO --> Using torch device: AMD Radeon RX 6800 XT

[2025-06-27 15:00:13,520]::[InvokeAI]::INFO --> cuDNN version: 3003000

[2025-06-27 15:00:14,906]::[InvokeAI]::INFO --> Patchmatch initialized

[2025-06-27 15:00:15,316]::[InvokeAI]::INFO --> InvokeAI version 5.15.0
[2025-06-27 15:00:15,316]::[InvokeAI]::INFO --> Root directory = /home/matias/AI/invokeai

[2025-06-27 15:00:15,317]::[InvokeAI]::INFO --> Initializing database at /home/matias/AI/invokeai/databases/invokeai.db

[2025-06-27 15:00:15,319]::[ModelManagerService]::INFO --> [MODEL CACHE] Calculated model RAM cache size: 12272.00 MB. Heuristics applied: [1, 2].

[2025-06-27 15:00:15,336]::[InvokeAI]::INFO --> Pruned 1 finished queue items

[2025-06-27 15:00:15,379]::[InvokeAI]::INFO --> Invoke running on http://127.0.0.1:9090 (Press CTRL+C to quit)

[2025-06-27 15:00:31,496]::[InvokeAI]::INFO --> Executing queue item 1860, session 44591bf5-c46d-479b-b8dc-3aceefce3675

Fetching 11 files:   0%|          | 0/11 [00:00<?, ?it/s]
Fetching 11 files: 100%|██████████| 11/11 [00:00<00:00, 99433.93it/s]

Loading pipeline components...:   0%|          | 0/6 [00:00<?, ?it/s]
Loading pipeline components...:  67%|██████▋   | 4/6 [00:00<00:00, 34.86it/s]
Loading pipeline components...: 100%|██████████| 6/6 [00:00<00:00, 12.12it/s]

[2025-06-27 15:00:32,917]::[ModelManagerService]::INFO --> [MODEL CACHE] Loaded model '9d7795e2-bdff-42d7-aae2-e63809a20377:text_encoder' (CLIPTextModel) onto cuda device in 0.22s. Total model size: 234.72MB, VRAM: 234.72MB (100.0%)

[2025-06-27 15:00:32,919]::[ModelManagerService]::INFO --> [MODEL CACHE] Loaded model '9d7795e2-bdff-42d7-aae2-e63809a20377:tokenizer' (CLIPTokenizer) onto cuda device in 0.00s. Total model size: 0.00MB, VRAM: 0.00MB (0.0%)

[2025-06-27 15:00:33,425]::[ModelManagerService]::INFO --> [MODEL CACHE] Loaded model '9d7795e2-bdff-42d7-aae2-e63809a20377:text_encoder' (CLIPTextModel) onto cuda device in 0.00s. Total model size: 234.72MB, VRAM: 234.72MB (100.0%)

[2025-06-27 15:00:33,426]::[ModelManagerService]::INFO --> [MODEL CACHE] Loaded model '9d7795e2-bdff-42d7-aae2-e63809a20377:tokenizer' (CLIPTokenizer) onto cuda device in 0.00s. Total model size: 0.00MB, VRAM: 0.00MB (0.0%)

Token indices sequence length is longer than the specified maximum sequence length for this model (88 > 77). Running this sequence through the model will result in indexing errors

[2025-06-27 15:00:33,682]::[ModelManagerService]::INFO --> [MODEL CACHE] Loaded model '9d7795e2-bdff-42d7-aae2-e63809a20377:unet' (UNet2DConditionModel) onto cuda device in 0.18s. Total model size: 1639.41MB, VRAM: 1639.41MB (100.0%)

[2025-06-27 15:00:33,687]::[ModelManagerService]::INFO --> [MODEL CACHE] Loaded model '9d7795e2-bdff-42d7-aae2-e63809a20377:scheduler' (PNDMScheduler) onto cuda device in 0.00s. Total model size: 0.00MB, VRAM: 0.00MB (0.0%)

  0%|          | 0/20 [00:00<?, ?it/s]
  0%|          | 0/20 [00:00<?, ?it/s]

[2025-06-27 15:00:33,977]::[InvokeAI]::ERROR --> Error while invoking session 44591bf5-c46d-479b-b8dc-3aceefce3675, invocation 1005ef11-e8e0-4951-9d01-1bece08bbcd5 (denoise_latents): HIP out of memory. Tried to allocate 16.00 GiB. GPU 0 has a total capacity of 15.98 GiB of which 13.26 GiB is free. Of the allocated memory 2.30 GiB is allocated by PyTorch, and 46.38 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_HIP_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
[2025-06-27 15:00:33,977]::[InvokeAI]::ERROR --> Traceback (most recent call last):
  File "/home/matias/AI/invokeai/.venv/lib/python3.12/site-packages/invokeai/app/services/session_processor/session_processor_default.py", line 130, in run_node
    output = invocation.invoke_internal(context=context, services=self._services)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matias/AI/invokeai/.venv/lib/python3.12/site-packages/invokeai/app/invocations/baseinvocation.py", line 241, in invoke_internal
    output = self.invoke(context)
             ^^^^^^^^^^^^^^^^^^^^
  File "/home/matias/AI/invokeai/.venv/lib/python3.12/site-packages/invokeai/app/invocations/denoise_latents.py", line 825, in invoke
    return self._old_invoke(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matias/AI/invokeai/.venv/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/matias/.local/share/uv/python/cpython-3.12.9-linux-x86_64-gnu/lib/python3.12/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/matias/AI/invokeai/.venv/lib/python3.12/site-packages/invokeai/app/invocations/denoise_latents.py", line 1088, in _old_invoke
    result_latents = pipeline.latents_from_embeddings(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matias/AI/invokeai/.venv/lib/python3.12/site-packages/invokeai/backend/stable_diffusion/diffusers_pipeline.py", line 397, in latents_from_embeddings
    step_output = self.step(
                  ^^^^^^^^^^
  File "/home/matias/AI/invokeai/.venv/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/matias/AI/invokeai/.venv/lib/python3.12/site-packages/invokeai/backend/stable_diffusion/diffusers_pipeline.py", line 548, in step
    uc_noise_pred, c_noise_pred = self.invokeai_diffuser.do_unet_step(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matias/AI/invokeai/.venv/lib/python3.12/site-packages/invokeai/backend/stable_diffusion/diffusion/shared_invokeai_diffusion.py", line 199, in do_unet_step
    ) = self._apply_standard_conditioning(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matias/AI/invokeai/.venv/lib/python3.12/site-packages/invokeai/backend/stable_diffusion/diffusion/shared_invokeai_diffusion.py", line 343, in _apply_standard_conditioning
    both_results = self.model_forward_callback(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matias/AI/invokeai/.venv/lib/python3.12/site-packages/invokeai/backend/stable_diffusion/diffusers_pipeline.py", line 611, in _unet_forward
    return self.unet(
           ^^^^^^^^^^
  File "/home/matias/AI/invokeai/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matias/AI/invokeai/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matias/AI/invokeai/.venv/lib/python3.12/site-packages/diffusers/models/unets/unet_2d_condition.py", line 1214, in forward
    sample, res_samples = downsample_block(
                          ^^^^^^^^^^^^^^^^^
  File "/home/matias/AI/invokeai/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matias/AI/invokeai/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matias/AI/invokeai/.venv/lib/python3.12/site-packages/diffusers/models/unets/unet_2d_blocks.py", line 1270, in forward
    hidden_states = attn(
                    ^^^^^
  File "/home/matias/AI/invokeai/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matias/AI/invokeai/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matias/AI/invokeai/.venv/lib/python3.12/site-packages/diffusers/models/transformers/transformer_2d.py", line 427, in forward
    hidden_states = block(
                    ^^^^^^
  File "/home/matias/AI/invokeai/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matias/AI/invokeai/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matias/AI/invokeai/.venv/lib/python3.12/site-packages/diffusers/models/attention.py", line 514, in forward
    attn_output = self.attn1(
                  ^^^^^^^^^^^
  File "/home/matias/AI/invokeai/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matias/AI/invokeai/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matias/AI/invokeai/.venv/lib/python3.12/site-packages/diffusers/models/attention_processor.py", line 605, in forward
    return self.processor(
           ^^^^^^^^^^^^^^^
  File "/home/matias/AI/invokeai/.venv/lib/python3.12/site-packages/diffusers/models/attention_processor.py", line 3313, in __call__
    hidden_states = F.scaled_dot_product_attention(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch.OutOfMemoryError: HIP out of memory. Tried to allocate 16.00 GiB. GPU 0 has a total capacity of 15.98 GiB of which 13.26 GiB is free. Of the allocated memory 2.30 GiB is allocated by PyTorch, and 46.38 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_HIP_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)


[2025-06-27 15:00:33,993]::[InvokeAI]::INFO --> Graph stats: 44591bf5-c46d-479b-b8dc-3aceefce3675
                          Node   Calls   Seconds  VRAM Used
             main_model_loader       1    0.013s     0.000G
                     clip_skip       1    0.001s     0.000G
                        compel       2    1.965s     0.270G
                       collect       2    0.001s     0.267G
                         noise       1    0.002s     0.267G
               denoise_latents       1    0.475s     2.298G
TOTAL GRAPH EXECUTION TIME:   2.456s
TOTAL GRAPH WALL TIME:   2.464s
RAM used by InvokeAI process: 4.06G (+2.557G)
RAM used to load models: 1.83G
VRAM in use: 1.886G
RAM cache statistics:
   Model cache hits: 6
   Model cache misses: 1
   Models cached: 5
   Models cleared from cache: 0
   Cache high water mark: 1.99/0.00G

```

# DEBUG VERSION

`PYTORCH_NO_HIP_MEMORY_CACHING=1` gets rid of any issues with PyTorch and could help getting to the bottom of the problem. I also use `AMD_SERIALIZE_KERNEL=3` as suggested.

```
AMD_SERIALIZE_KERNEL=3 PYTORCH_NO_HIP_MEMORY_CACHING=1 "/home/matias/AI/invokeai/Invoke Community Edition.AppImage"

Starting up...
Started Invoke process with PID: 28383
bitsandbytes library load error: Configured CUDA binary not found at /home/matias/AI/invokeai/.venv/lib/python3.12/site-packages/bitsandbytes/libbitsandbytes_rocm63.so
Traceback (most recent call last):
  File "/home/matias/AI/invokeai/.venv/lib/python3.12/site-packages/bitsandbytes/cextension.py", line 290, in <module>
    lib = get_native_library()
          ^^^^^^^^^^^^^^^^^^^^
  File "/home/matias/AI/invokeai/.venv/lib/python3.12/site-packages/bitsandbytes/cextension.py", line 270, in get_native_library
    raise RuntimeError(f"Configured CUDA binary not found at {cuda_binary_path}")
RuntimeError: Configured CUDA binary not found at /home/matias/AI/invokeai/.venv/lib/python3.12/site-packages/bitsandbytes/libbitsandbytes_rocm63.so
[2025-06-27 14:56:43,131]::[InvokeAI]::INFO --> Using torch device: AMD Radeon RX 6800 XT
[2025-06-27 14:56:43,133]::[InvokeAI]::INFO --> cuDNN version: 3003000
[2025-06-27 14:56:44,558]::[InvokeAI]::INFO --> Patchmatch initialized
[2025-06-27 14:56:44,968]::[InvokeAI]::INFO --> InvokeAI version 5.15.0
[2025-06-27 14:56:44,968]::[InvokeAI]::INFO --> Root directory = /home/matias/AI/invokeai
[2025-06-27 14:56:44,969]::[InvokeAI]::INFO --> Initializing database at /home/matias/AI/invokeai/databases/invokeai.db
[2025-06-27 14:56:44,971]::[ModelManagerService]::INFO --> [MODEL CACHE] Calculated model RAM cache size: 12272.00 MB. Heuristics applied: [1, 2].
[2025-06-27 14:56:44,988]::[InvokeAI]::INFO --> Pruned 1 finished queue items
[2025-06-27 14:56:45,030]::[InvokeAI]::INFO --> Invoke running on http://127.0.0.1:9090/ (Press CTRL+C to quit)
[2025-06-27 14:57:10,399]::[InvokeAI]::INFO --> Executing queue item 1859, session 8b2c4752-61ff-49a1-b88f-4e6a23adf186

Fetching 11 files:   0%|          | 0/11 [00:00<?, ?it/s]
Fetching 11 files: 100%|██████████| 11/11 [00:00<00:00, 70762.80it/s]

Loading pipeline components...:   0%|          | 0/6 [00:00<?, ?it/s]
Loading pipeline components...:  67%|██████▋   | 4/6 [00:00<00:00, 33.70it/s]
Loading pipeline components...: 100%|██████████| 6/6 [00:00<00:00, 11.60it/s]
[2025-06-27 14:57:11,828]::[ModelManagerService]::INFO --> [MODEL CACHE] Loaded model '9d7795e2-bdff-42d7-aae2-e63809a20377:text_encoder' (CLIPTextModel) onto cuda device in 0.22s. Total model size: 234.72MB, VRAM: 234.72MB (100.0%)
[2025-06-27 14:57:11,830]::[ModelManagerService]::INFO --> [MODEL CACHE] Loaded model '9d7795e2-bdff-42d7-aae2-e63809a20377:tokenizer' (CLIPTokenizer) onto cuda device in 0.00s. Total model size: 0.00MB, VRAM: 0.00MB (0.0%)
[2025-06-27 14:57:12,363]::[ModelManagerService]::INFO --> [MODEL CACHE] Loaded model '9d7795e2-bdff-42d7-aae2-e63809a20377:text_encoder' (CLIPTextModel) onto cuda device in 0.00s. Total model size: 234.72MB, VRAM: 234.72MB (100.0%)
[2025-06-27 14:57:12,365]::[ModelManagerService]::INFO --> [MODEL CACHE] Loaded model '9d7795e2-bdff-42d7-aae2-e63809a20377:tokenizer' (CLIPTokenizer) onto cuda device in 0.00s. Total model size: 0.00MB, VRAM: 0.00MB (0.0%)
Token indices sequence length is longer than the specified maximum sequence length for this model (88 > 77). Running this sequence through the model will result in indexing errors
[2025-06-27 14:57:12,685]::[ModelManagerService]::INFO --> [MODEL CACHE] Loaded model '9d7795e2-bdff-42d7-aae2-e63809a20377:unet' (UNet2DConditionModel) onto cuda device in 0.18s. Total model size: 1639.41MB, VRAM: 1639.41MB (100.0%)
[2025-06-27 14:57:12,690]::[ModelManagerService]::INFO --> [MODEL CACHE] Loaded model '9d7795e2-bdff-42d7-aae2-e63809a20377:scheduler' (PNDMScheduler) onto cuda device in 0.00s. Total model size: 0.00MB, VRAM: 0.00MB (0.0%)

  0%|          | 0/20 [00:00<?, ?it/s]
  0%|          | 0/20 [00:00<?, ?it/s]
[2025-06-27 14:57:12,985]::[InvokeAI]::ERROR --> Error while invoking session 8b2c4752-61ff-49a1-b88f-4e6a23adf186, invocation f2ff1fd8-587f-49de-8d0d-2c33b665d01e (denoise_latents): HIP error: out of memory
HIP kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing AMD_SERIALIZE_KERNEL=3
Compile with `TORCH_USE_HIP_DSA` to enable device-side assertions.
[2025-06-27 14:57:12,985]::[InvokeAI]::ERROR --> Traceback (most recent call last):
  File "/home/matias/AI/invokeai/.venv/lib/python3.12/site-packages/invokeai/app/services/session_processor/session_processor_default.py", line 130, in run_node
    output = invocation.invoke_internal(context=context, services=self._services)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matias/AI/invokeai/.venv/lib/python3.12/site-packages/invokeai/app/invocations/baseinvocation.py", line 241, in invoke_internal
    output = self.invoke(context)
             ^^^^^^^^^^^^^^^^^^^^
  File "/home/matias/AI/invokeai/.venv/lib/python3.12/site-packages/invokeai/app/invocations/denoise_latents.py", line 825, in invoke
    return self._old_invoke(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matias/AI/invokeai/.venv/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/matias/.local/share/uv/python/cpython-3.12.9-linux-x86_64-gnu/lib/python3.12/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/matias/AI/invokeai/.venv/lib/python3.12/site-packages/invokeai/app/invocations/denoise_latents.py", line 1088, in _old_invoke
    result_latents = pipeline.latents_from_embeddings(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matias/AI/invokeai/.venv/lib/python3.12/site-packages/invokeai/backend/stable_diffusion/diffusers_pipeline.py", line 397, in latents_from_embeddings
    step_output = self.step(
                  ^^^^^^^^^^
  File "/home/matias/AI/invokeai/.venv/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/matias/AI/invokeai/.venv/lib/python3.12/site-packages/invokeai/backend/stable_diffusion/diffusers_pipeline.py", line 548, in step
    uc_noise_pred, c_noise_pred = self.invokeai_diffuser.do_unet_step(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matias/AI/invokeai/.venv/lib/python3.12/site-packages/invokeai/backend/stable_diffusion/diffusion/shared_invokeai_diffusion.py", line 199, in do_unet_step
    ) = self._apply_standard_conditioning(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matias/AI/invokeai/.venv/lib/python3.12/site-packages/invokeai/backend/stable_diffusion/diffusion/shared_invokeai_diffusion.py", line 343, in _apply_standard_conditioning
    both_results = self.model_forward_callback(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matias/AI/invokeai/.venv/lib/python3.12/site-packages/invokeai/backend/stable_diffusion/diffusers_pipeline.py", line 611, in _unet_forward
    return self.unet(
           ^^^^^^^^^^
  File "/home/matias/AI/invokeai/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matias/AI/invokeai/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matias/AI/invokeai/.venv/lib/python3.12/site-packages/diffusers/models/unets/unet_2d_condition.py", line 1214, in forward
    sample, res_samples = downsample_block(
                          ^^^^^^^^^^^^^^^^^
  File "/home/matias/AI/invokeai/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matias/AI/invokeai/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matias/AI/invokeai/.venv/lib/python3.12/site-packages/diffusers/models/unets/unet_2d_blocks.py", line 1270, in forward
    hidden_states = attn(
                    ^^^^^
  File "/home/matias/AI/invokeai/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matias/AI/invokeai/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matias/AI/invokeai/.venv/lib/python3.12/site-packages/diffusers/models/transformers/transformer_2d.py", line 427, in forward
    hidden_states = block(
                    ^^^^^^
  File "/home/matias/AI/invokeai/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matias/AI/invokeai/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matias/AI/invokeai/.venv/lib/python3.12/site-packages/diffusers/models/attention.py", line 514, in forward
    attn_output = self.attn1(
                  ^^^^^^^^^^^
  File "/home/matias/AI/invokeai/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matias/AI/invokeai/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matias/AI/invokeai/.venv/lib/python3.12/site-packages/diffusers/models/attention_processor.py", line 605, in forward
    return self.processor(
           ^^^^^^^^^^^^^^^
  File "/home/matias/AI/invokeai/.venv/lib/python3.12/site-packages/diffusers/models/attention_processor.py", line 3313, in __call__
    hidden_states = F.scaled_dot_product_attention(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: HIP error: out of memory
HIP kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing AMD_SERIALIZE_KERNEL=3
Compile with `TORCH_USE_HIP_DSA` to enable device-side assertions.
[2025-06-27 14:57:13,003]::[InvokeAI]::INFO --> Graph stats: 8b2c4752-61ff-49a1-b88f-4e6a23adf186
                          Node   Calls   Seconds  VRAM Used
             main_model_loader       1    0.010s     0.000G
                     clip_skip       1    0.001s     0.000G
                        compel       2    2.073s     0.000G
                       collect       2    0.001s     0.000G
                         noise       1    0.002s     0.000G
               denoise_latents       1    0.482s     0.000G
TOTAL GRAPH EXECUTION TIME:   2.567s
TOTAL GRAPH WALL TIME:   2.572s
RAM used by InvokeAI process: 4.06G (+2.559G)
RAM used to load models: 1.83G
RAM cache statistics:
   Model cache hits: 6
   Model cache misses: 1
   Models cached: 5
   Models cleared from cache: 0
   Cache high water mark: 1.99/0.00G
```

**Comment by SadmL** [comment]
I have RX 6700 XT with 12GB VRAM

This helped me get out of OOM

# invokeai.yaml
```
device_working_mem_gb: 10
precision: float16
```

# Environtment variables

`max_split_size_mb:512` cause OOM, increasing to 4096 helps

```
PYTORCH_HIP_ALLOC_CONF=garbage_collection_threshold:0.9,max_split_size_mb:4096
```

Using inpaint layer 5-8/12 GB is utilized, takes some mins, but works without OOM, but still can't generate additions to image on empty space, getting error 
`RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory`, as here https://github.com/invoke-ai/InvokeAI/issues/7750

**Comment by darksylinc** [comment]
I forgot to post my results:

Ubuntu 24.04 LTS
AMD Radeon HD 6800 XT 16GB VRAM
32 GB RAM

I've been testing for weeks and OOM are a thing of the past for me (as long as I stick to known working resolutions).

# No more OOMs

This includes inpaint layers and control nets.

SD 1.5 for resolutions:
 - <= 768x768 verified
 - 1024x1024 -> I didn't test inpaint and CN.

SDXL for resolutions:
 - 1024x1024
 - 1368x768 / 768x1368
 - 1256x840 / 840x1256
 - 1184x888 / 888x1184
 - Higher resolutions may work but you may run into issues

## Environment variables:

```bash
env PYTORCH_HIP_ALLOC_CONF=garbage_collection_threshold:0.4,max_split_size_mb:256 "/home/username/AI/invokeai/Invoke Community Edition.AppImage"
```

## invokeai.yaml

```yaml
# Internal metadata - do not edit:
schema_version: 4.0.2

# Put user settings here - see https://invoke-ai.github.io/InvokeAI/configuration/:
enable_partial_loading: true
precision: float16
device_working_mem_gb: 4
sequential_guidance: true
force_tiled_decode: true

attention_type: sliced
attention_slice_size: 8
```

Note that the attention slice settings are very important!

# Troubleshooting Guide

Most people post their results with very high `garbage_collection_threshold`. A lower value makes garbage collection _more aggressive_, which is what we want to reclaim memory.

If you see the error:

```
Tried to allocate 4.03 GiB. GPU 0 has a total capacity of 15.98 GiB of which 5.28 GiB is free
```

The numbers that matter is 4.03GiB (how much InvokeAI needed) and 5.28GiB (how much space was available).

That means you _**can**_ fix it because the GPU had enough memory, but it was too fragmented (it's like playing a game of tetris. you have lots empty space but it's all scattered and still lose the game).

You can fix this by lowering `garbage_collection_threshold` or maybe lowering `max_split_size_mb` (or sometimes increasing it).

This can also be fixed by restarting InvokeAI, because it's like starting a new empty Tetris match.


**However if you see the opposite error:**

```
Tried to allocate 5.03 GiB. GPU 0 has a total capacity of 15.98 GiB of which 4.28 GiB is free
```

That means InvokeAI tried to allocate more VRAM than was available. It __might__ get fixed by restarting InvokeAI; but this is difficult to fix. It has to do with pytorch optimizations for ROCm, and maybe invokeai.

The best solution is to lower resolution or remove masks / CNs.


**And if you see the following error:**

```
Tried to allocate 18.25 GiB. GPU 0 has a total capacity of 15.98 GiB of which 4.28 GiB is free
```

Forget about it, InvokeAI is trying to use more VRAM than your GPU has. That's never going to work without a pytorch or invokeai fix.

This is the case of SD 1.5 when using 1024x1024. It wants to use 16GiB of VRAM, on a 16GiB card (which is impossible because _something_ needs to be left for the OS).

**Comment by darksylinc** [comment]
@psychedelicious apologies for pinging directly.

Looking up online I see that the problem appears to be that on AMD ROCm has [their own build of xfomers](https://github.com/ROCm/xformers/) to use CK (Composable Kernels) and thus be able to take advantage memory-optimized Flash-Attention, but is supported on a _very_ limited amount of AMD Hardware (see https://github.com/ROCm/composable_kernel/issues/1434 and https://github.com/ROCm/composable_kernel/issues/1958).

I'm looking over the `.venv` folder directly and I see that the xformers project isn't used directly, but InvokeAI has the `xformers` setting in `attention_type` so I guess it must be included _somewhere_, yet I can't find it.

Can you hint me on where should I look into so that I can toy with replacing the module for one built with ROCm in mind? (I hope it's not already included in torch-2.7.1+rocm6.3 / torchvision-0.22.1+rocm6.3 / pytorch_triton_rocm-3.3.1 or if it is, that it is disabled for some reason). Or is xformers not used at all? Or do you use an alternate implementation written from another project?

**Update:**

I modified invokeai to print me some useful info:
```
prefer_xformers: False
is_xformers_available: False
```

Well I guess that explains what I was seeing. `xformers` is not even included. Is this normal / expected?

**Comment by darksylinc** [comment]
**Update:** I managed SD 1.5 1024x1024 to work using the config:

```yaml
attention_type: sliced
attention_slice_size: 8
```

I've [updated my guide](https://github.com/invoke-ai/InvokeAI/issues/6301#issuecomment-3070191980).

**Update 2:** Generation speed also improved. For SDXL 888x1184 generation time (using default attention type) went from 27.85s (avg) down to 20.11s (avg). For SD 1.5 512x512 it went from 4.84 to 2.92.

These improvements are huge.

Is there a benchmark CLI to test? I think InvokeAI could strongly reconsider using different default settings for AMD after doing more testing.

**Update 3:** There are no noticeable performance differences between `attention_slice_size` 4 vs 8. So I guess 8 should be preferred since in theory it uses less VRAM.

**Update 4:** Now that this setting has freed a lot of VRAM, I can disable `sequential_guidance` and now SDXL 888x1184 generation time is down to 18s.

**Comment by psychedelicious** [comment]
@darksylinc 
I don't think any of the Invoke code contributors have an AMD card. Your testing and investigation is greatly appreciated.

> Can you hint me on where should I look into so that I can toy with replacing the module for one built with ROCm in mind? (I hope it's not already included in torch-2.7.1+rocm6.3 / torchvision-0.22.1+rocm6.3 / pytorch_triton_rocm-3.3.1 or if it is, that it is disabled for some reason). Or is xformers not used at all? Or do you use an alternate implementation written from another project?

If you installed with the Invoke Launcher, xformers is installed if you select `< 30xx` as your GPU type. PyTorch's included SDP implementation is much faster than xformers for 30xx series GPUs and above. So we only install it for < 30xx series. If you select AMD, it isn't installed.

If you did a manual install, you need to add the `xformers` extra to the package specifier, as described in step 6 of the manual install instructions: https://invoke-ai.github.io/InvokeAI/installation/manual/#walkthrough

If you want to manually modify packages, for a Launcher install, click the dev console button and then you can use the pre-installed [uv](https://docs.astral.sh/uv/) to do whatever you need to do. It provides a pip-compatible interface - just prefix a normal pip command with "uv" e.g. `uv pip install torch`.

> Is there a benchmark CLI to test?

No, and I'm not aware of any tooling to do this. You could do something like this:
- Install all the models you want to test with
- Pause the processor (menu button next to the Invoke button)
- Queue up the generations you want to include in the benchmark
- Shut down the app
- Copy the `invokeai.db` file, which includes your pending queue

Now you have a database that has your test suite ready to go. For each test case of settings, overwrite the existing DB with the one you seeded with a queue, start the app and let it run. Review either the queue results directly or the terminal outputs.

> I think InvokeAI could strongly reconsider using different default settings for AMD after doing more testing.

We'd be very happy to review a PR that sets this up.

**Comment by darksylinc** [comment]
> If you installed with the Invoke Launcher, xformers is installed if you select < 30xx as your GPU type. PyTorch's included SDP implementation is much faster than xformers for 30xx series GPUs and above. So we only install it for < 30xx series. If you select AMD, it isn't installed.

Ah! That makes sense! I tried installing the >= 30xx series, and saw xformers wasn't there either. Now I know why :)

> If you did a manual install, you need to add the xformers extra to the package specifier, as described in step 6 of the manual install instructions: https://invoke-ai.github.io/InvokeAI/installation/manual/#walkthrough

Ah! Thanks for the pointers! I need to RTFM.

> Shut down the app
> Copy the invokeai.db file, which includes your pending queue

Interesting trick. I'll keep that in mind!


> We'd be very happy to review a PR that sets this up.

Thanks! Before submitting a PR I want to test this new setting combination for a few weeks. My plan was basically:

1. I want to check out (ROCm version of) xformers but only if it doesn't take me too much time. AFAICT it needs a lengthy compilation process. Furthermore it's not compatible with many models (including the 7900 XT which is ridiculous). But if I get some time, I'd want to (my model happens to be among the lucky few supported). TBH the whole pytorch / AI ecosystem looks daunting. It's too obvious it grew organically for prototyping, and now it's a Frankenstein monster.
2. I want to try the new settings for a few weeks to see stability and performance before submitting any PRs.
3. According to [Comfy-UI](https://github.com/comfyanonymous/ComfyUI/wiki/Which-GPU-should-I-buy-for-ComfyUI) AMD "...lack of an optimized implementation of torch.nn.functional.scaled_dot_product_attention for consumer GPUs". Considering that evidence points to SDP __being__ the source of the OoM situation, this checks out.
4. The low hanging fruit for an AMD-based PR would be to tweak defaults:
   - Sliced attention type and set to 8 slices.
   - Tiled decode on.
   - Probably sequential guidance on true to reduce OoM.
5. If I get time, explore the possibility of using xformers with CK where supported (and assuming it improves perf / memory usage).

Slicing giving higher performance doesn't surprise me. AMD GPUs favor more smaller kernels over few big ones.
I didn't benchmark tiled decode numbers but I wouldn't be surprised if it doesn't affect perf negatively.

I cannot promise anything, because again, I'm very limited with time through work. I'm exploring AI as a side project and InvokeAI was the first app I saw that got UI and UX right (from installation to final image output).
