### ISSUE TITLE
[bug]: RTX 5090 support missing

### ISSUE THREAD

**Issue by GewoonJaap** [invoke-ai/InvokeAI#7683]
### Is there an existing issue for this problem?

- [x] I have searched the existing issues

### Operating system

Windows

### GPU vendor

Nvidia (CUDA)

### GPU model

RTX 5090 FE

### GPU VRAM

32GB

### Version number

5.6.2

### Browser

Firefox

### Python dependencies

{
  "accelerate": "1.0.1",
  "compel": "2.0.2",
  "cuda": "12.4",
  "diffusers": "0.31.0",
  "numpy": "1.26.4",
  "opencv": "4.9.0.80",
  "onnx": "1.16.1",
  "pillow": "11.1.0",
  "python": "3.10.11",
  "torch": "2.4.1+cu124",
  "torchvision": "0.19.1+cu124",
  "transformers": "4.46.3",
  "xformers": "0.0.28.post1"
}

### What happened

Getting the following error while trying to generate an image:

```
Error while invoking session d47d1ba3-bc52-4d04-b425-ce08a91d84df, invocation 28b7c880-8463-4e2c-8ed2-4c674f25a610 (flux_text_encoder): CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

[2025-02-25 19:18:26,153]::[InvokeAI]::ERROR --> Traceback (most recent call last):
  File "C:\Users\Jaap\AppData\Roaming\StabilityMatrix\Packages\InvokeAI\invokeai\app\services\session_processor\session_processor_default.py", line 129, in run_node
    output = invocation.invoke_internal(context=context, services=self._services)
  File "C:\Users\Jaap\AppData\Roaming\StabilityMatrix\Packages\InvokeAI\invokeai\app\invocations\baseinvocation.py", line 300, in invoke_internal
    output = self.invoke(context)
  File "C:\Users\Jaap\AppData\Roaming\StabilityMatrix\Packages\InvokeAI\venv\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Jaap\AppData\Roaming\StabilityMatrix\Packages\InvokeAI\invokeai\app\invocations\flux_text_encoder.py", line 60, in invoke
    t5_embeddings = self._t5_encode(context)
  File "C:\Users\Jaap\AppData\Roaming\StabilityMatrix\Packages\InvokeAI\invokeai\app\invocations\flux_text_encoder.py", line 78, in _t5_encode
    with (
  File "contextlib.py", line 135, in __enter__
  File "C:\Users\Jaap\AppData\Roaming\StabilityMatrix\Packages\InvokeAI\invokeai\backend\model_manager\load\load_base.py", line 75, in model_on_device
    self._cache.lock(self._cache_record, working_mem_bytes)
  File "C:\Users\Jaap\AppData\Roaming\StabilityMatrix\Packages\InvokeAI\invokeai\backend\model_manager\load\model_cache\model_cache.py", line 52, in wrapper
    return method(self, *args, **kwargs)
  File "C:\Users\Jaap\AppData\Roaming\StabilityMatrix\Packages\InvokeAI\invokeai\backend\model_manager\load\model_cache\model_cache.py", line 256, in lock
    self._load_locked_model(cache_entry, working_mem_bytes)
  File "C:\Users\Jaap\AppData\Roaming\StabilityMatrix\Packages\InvokeAI\invokeai\backend\model_manager\load\model_cache\model_cache.py", line 328, in _load_locked_model
    model_bytes_loaded = self._move_model_to_vram(cache_entry, vram_available + MB)
  File "C:\Users\Jaap\AppData\Roaming\StabilityMatrix\Packages\InvokeAI\invokeai\backend\model_manager\load\model_cache\model_cache.py", line 350, in _move_model_to_vram
    return cache_entry.cached_model.full_load_to_vram()
  File "C:\Users\Jaap\AppData\Roaming\StabilityMatrix\Packages\InvokeAI\invokeai\backend\model_manager\load\model_cache\cached_model\cached_model_only_full_load.py", line 78, in full_load_to_vram
    self._model.load_state_dict(new_state_dict, assign=True)
  File "C:\Users\Jaap\AppData\Roaming\StabilityMatrix\Packages\InvokeAI\venv\lib\site-packages\torch\nn\modules\module.py", line 2201, in load_state_dict
    load(self, state_dict)
  File "C:\Users\Jaap\AppData\Roaming\StabilityMatrix\Packages\InvokeAI\venv\lib\site-packages\torch\nn\modules\module.py", line 2189, in load
    load(child, child_state_dict, child_prefix)  # noqa: F821
  File "C:\Users\Jaap\AppData\Roaming\StabilityMatrix\Packages\InvokeAI\venv\lib\site-packages\torch\nn\modules\module.py", line 2189, in load
    load(child, child_state_dict, child_prefix)  # noqa: F821
  File "C:\Users\Jaap\AppData\Roaming\StabilityMatrix\Packages\InvokeAI\venv\lib\site-packages\torch\nn\modules\module.py", line 2189, in load
    load(child, child_state_dict, child_prefix)  # noqa: F821
  [Previous line repeated 4 more times]
  File "C:\Users\Jaap\AppData\Roaming\StabilityMatrix\Packages\InvokeAI\venv\lib\site-packages\torch\nn\modules\module.py", line 2183, in load
    module._load_from_state_dict(
  File "C:\Users\Jaap\AppData\Roaming\StabilityMatrix\Packages\InvokeAI\invokeai\backend\quantization\bnb_llm_int8.py", line 58, in _load_from_state_dict
    assert weight_format == 0
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

### What you expected to happen

I expected an image to be generated

### How to reproduce the problem

Bootup Invoke.AI on a RTX 50xx card
Generate an image
Observe the error.

### Additional context

Seems like a new CUDA version is being used by the RT50 series cards:
https://github.com/lllyasviel/Fooocus/issues/3862#issuecomment-2662913403

**Comment by GewoonJaap** [comment]
```
C:\Users\Jaap\AppData\Roaming\StabilityMatrix\Packages\InvokeAI\venv\lib\site-packages\torch\cuda\__init__.py:230: UserWarning: 
NVIDIA GeForce RTX 5090 with CUDA capability sm_120 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_50 sm_60 sm_61 sm_70 sm_75 sm_80 sm_86 sm_90.
If you want to use the NVIDIA GeForce RTX 5090 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

```

**Comment by Andyx1976** [comment]
sadly not an option if one uses the launcher.  i think comfyui has it's first monthyversary of supporting 50xx coming up.

**Comment by GewoonJaap** [comment]
> sadly not an option if one uses the launcher. i think comfyui has it's first monthyversary of supporting 50xx coming up.

Why not? Using updated packages that support the new CUDA version should fixt it?

**Comment by Andyx1976** [comment]
the entire thing with the launcher is that i t does all that automatically (yes, for noobs, that's me). and it installs an "old" version. maybe If it would run with a nightly 12.8 build but idk how.

**Comment by GewoonJaap** [comment]
Ah I understand. Yeah with the StabilityMatrix launcher you have to option to override the Python modules or use a different version of invokeAI. I override the pytorch modules but then xformers start throwing compatibility errors because they also haven't updated

**Comment by GewoonJaap** [comment]
Anyplan to support RTX 50 series?

**Comment by Andyx1976** [comment]
i managed to do it with the latest pytorch and it worked fine. "Thankfully" the stupid launcher"updated a newer pytorch with the old one. Even the most basic installer questions if a newer version should be removed.
So trying to remember and doing it again. i update here in a moment. Needs python of course.

**Comment by Andyx1976** [comment]
So, don't worry it looks way more complicated than it is.
the short version: no, the pip pytorch alone didn't work, it installed but invoke gave me a cuda kernel error. . 
But i only needed to use uv (invoke uses this in their full manual installation instructions too).  which installs some other needed stuff automatically. But with that it was all it needed.

So here is the noob version that i would have needed. sorry for the pros :)  Python installed, prompt going.
 you also need uv installed, which does install some requirements automatically.  For that at https://docs.astral.sh/uv/getting-started/installation/ they have a simple windows setup-launcher among other ways. then:
go to  pytorch.org/get-started/locally/    At the bottom select:  nightly, windows, pip, cuda 12.8.  Copy the code  and add uv up front and --force-reinstall at the back. that gives you:

`uv pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu128 --force-reinstall
`
now go to the invoke root directory (where you should see a .venv, models, outputs and so on folder. Open a powershell or whatever  prompt here:
enter 
`.venv\Scripts\activate`
to activate... nevermind. And then the magic formula:
`uv pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu128 --force-reinstall`

it should start downloading and doing things. when it's done, i can start invoke normally with the launcher and runs no issues with my 5080. 
--
 However during launch you see this error rolling by:  
"Could not find the bitsandbytes CUDA binary at WindowsPath('X:/XXXX/invoke/.venv/Lib/site-packages/bitsandbytes/libbitsandbytes_cuda128.dll')
The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable."

i had the same issue (and working RTX5080 solution btw!) with Fluxgym.  Bits and bytes has an update, which our glorious launcher also doesn't know and probably overwrites next patch. So go down to this directory ( /invoke/.venv/Lib/site-packages ) delete the old bitsandbytes folder, open a prompt and do (git being instaleld of course)
git clone https://github.com/bitsandbytes-foundation/bitsandbytes.git

**Comment by LeastyBeasty** [comment]
Went through this a few days ago and it's been working fine. Wanted to share, as it's slightly different from the others.

I'm on Windows 11, using RTX 5090.

First of all, I was using the Invoke Installer, and it doesn't include the pip module in the .venv, so I was having trouble trying to manually install cuda128. When I ran the pip commands, it ended up using the system pip, which installed the new torch versions to the wrong place.

You can determine where the pip is by doing `where pip` (on Windows like me) or `which pip` for unix type systems I think.

So, basically I had to go in to my directory, as others have stated, and activate the environment.

`.venv\Scripts\activate`

Then I had to install the missing pip module

`py -m ensurepip --default-pip`

To confirm it installed to the .venv, I typed `where pip` and verified it had it listed in the .venv path.

Now we just reinstall torch with the proper cuda version:

`pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu128 --force-reinstall`

Once that is done, start up Invoke and it should work! Hope that helps someone.

**Comment by LeastyBeasty** [comment]
Thanks for the tip about uv. 

Things have been working well except it seems like my images don't save the prompt in the metadata. When I recall metadata, everything else is saved except the prompt. Have you experienced this?

**Comment by kernkraft235** [comment]
I just used the vast.ai cuda 12.8 template and compiled xformers from source
For BNB I set env var BNB_CUDA_VERSION=128 and installed v0.45.3 which is the first release with blackwell support

```bash


# we are overriding some of the requirements so I install invokeai first
pip install --pre invokeai

# now torch nightly for CUDA 12.8
pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu128

# Now Xformers, we must build from source, it will claim it can't find torch w/o no-build-isolation
pip install -v -U git+https://github.com/facebookresearch/xformers.git@main#egg=xformers --no-deps --no-build-isolation

# InvokeAI ran without BNB getting updated but gave errors/warnings on start
export BNB_CUDA_VERSION=128
pip install --force-reinstall 'https://github.com/bitsandbytes-foundation/bitsandbytes/releases/download/continuous-release_main/bitsandbytes-0.45.3.dev0-py3-none-manylinux_2_24_x86_64.whl' --no-deps`

# Might as well fix pypatchmatch too
sudo apt install python3-opencv libopencv-dev
pip install pypatchmatch
```

It tries to install pytorch 2.6 so thats why I added no-deps
Anecdotally, before fixing BNB i was getting SDXL 1024x1024 in 6 seconds. After updating BNB to a version that supports CUDA 12.8 and blackwell I noticed it was about 3 to 4 seconds. With Hyper lora I was down to 1s per image

**Comment by drexlma** [comment]
> pip install -v -U git+https://github.com/facebookresearch/xformers.git@main#egg=xformers --no-deps --no-build-isolation



> I just used the vast.ai cuda 12.8 template and compiled xformers from source For BNB I set env var BNB_CUDA_VERSION=128 and installed v0.45.3 which is the first release with blackwell support
> 
> # we are overriding some of the requirements so I install invokeai first
> pip install --pre invokeai
> 
> # now torch nightly for CUDA 12.8
> pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu128
> 
> # Now Xformers, we must build from source, it will claim it can't find torch w/o no-build-isolation
> pip install -v -U git+https://github.com/facebookresearch/xformers.git@main#egg=xformers --no-deps --no-build-isolation
> 
> # InvokeAI ran without BNB getting updated but gave errors/warnings on start
> export BNB_CUDA_VERSION=128
> pip install --force-reinstall 'https://github.com/bitsandbytes-foundation/bitsandbytes/releases/download/continuous-release_main/bitsandbytes-0.45.3.dev0-py3-none-manylinux_2_24_x86_64.whl' --no-deps`
> 
> # Might as well fix pypatchmatch too
> sudo apt install python3-opencv libopencv-dev
> pip install pypatchmatch
> It tries to install pytorch 2.6 so thats why I added no-deps Anecdotally, before fixing BNB i was getting SDXL 1024x1024 in 6 seconds. After updating BNB to a version that supports CUDA 12.8 and blackwell I noticed it was about 3 to 4 seconds. With Hyper lora I was down to 1s per image

This works also with NVIDIA GeForce RTX 5070 Ti, i only use uv in docker 

`uv pip install --pre invokeai
uv pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu128
uv pip install -v -U git+https://github.com/facebookresearch/xformers.git@main#egg=xformers --no-deps --no-build-isolation
export BNB_CUDA_VERSION=128
apt install python3-opencv libopencv-dev
uv pip install pypatchmatch`

then restart container


i dont need this:
> pip install -v -U git+https://github.com/facebookresearch/xformers.git@main#egg=xformers --no-deps --no-build-isolation

**Comment by Andyx1976** [comment]
> Thanks for the tip about uv.
> 
> Things have been working well except it seems like my images don't save the prompt in the metadata. When I recall metadata, everything else is saved except the prompt. Have you experienced this?

nope. It works perfectly normal for me.  Maybe reinstall invoke again? It's a new version out anyway, so do that and then pytorch again. update bitsandbytes, i added the professional way to do it. 
But i honestly  I doubt that meta thingy function  has anything to do with what we touched here.

**Comment by Andyx1976** [comment]
but i assume the requirements that uv goes for in the full package list have these old versions too? Because the launcher doesn't anythign else, really.  i do the launcher and then the above two things.  Or does --pre help there? never tried.
Only i forgot in the later post the link to the pytorch selection page. There might be a new or maybe not nightly build version and my link would be bad.

**Comment by Little-God1983** [comment]
Cannot install bitsandbytes
i do this: pip install --force-reinstall --no-cache-dir bitsandbytes
then a lot gets uninstalled, downloaded and reinstalled.
But then?
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchaudio 2.6.0.dev20250326+cu128 requires torch==2.8.0.dev20250325+cu128, but you have torch 2.6.0 which is incompatible.
torchvision 0.22.0.dev20250326+cu128 requires torch==2.8.0.dev20250325+cu128, but you have torch 2.6.0 which is incompatible.
I dont know how to upgrade torch.
I already did:
uv pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu128 --force-reinstall

**Comment by Andyx1976** [comment]
i get the error message too because i do it before the torch update (for that reason it it doesnt overwrite the pytorch stuff . that is normal.  but after the uv pip torch thing that very stuff gets installed and after that i can launch invoke.  If you can´t it seems more like the pytorch command goes wrong.... I´m no expert and no good for trouble shooting. i found one solution that works for me and try  not to stray from the path. 

When you do the uv pip torch thing it should do a long series of downloads and stuff and then it works . Does it do that? If not maybe uv isn´t correctly installed?    Also i use my solution (in windows) from the version that the  invoke launcher installs. I let it do its thing and than do my 3 lines. 
But i did the same to fluxgym and onetrainer and it worked too.

**Comment by mgrugl** [comment]
@Andyx1976 @LeastyBeasty Many thanks, your tips work for my 5090. I'd assume the Invoke devs are aware of the need to support 50xx gen cards, but perhaps you would consider a PR.

**Comment by Andyx1976** [comment]
> [@Andyx1976](https://github.com/Andyx1976) [@LeastyBeasty](https://github.com/LeastyBeasty) Many thanks, your tips work for my 5090. I'd assume the Invoke devs are aware of the need to support 50xx gen cards, but perhaps you would consider a PR.

i strongly suspect they wait until that cuda version moves from nightly to stable. But a option in the launcher would be good.  I'm also absolutely sure they are aware of this.

**Comment by AlexGreenEyes** [comment]
Is it possible to somehow fix this error?

```
Could not find the bitsandbytes CUDA binary at WindowsPath('D:/test/.venv/Lib/site-packages/bitsandbytes/libbitsandbytes_cuda128.dll')
The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
```

Following the advice from the commen https://github.com/invoke-ai/InvokeAI/issues/7683#issuecomment-2717003528

**Comment by Andyx1976** [comment]
it seems when you follow the manual install and when installing the package use `uv pip install --pre invokeai --python 3.12 --python-preference only-managed --force-reinstall`
it installs the cu128 pytorch and the new bitsandbytes.

**Comment by Andyx1976** [comment]
### Update, simplified solution now: As of Version 9.10 The community edition launcher (and presumably the manual one) installs a correct (modern) version of Bits and Bytes. So the only thing to be done is the pytorch command.` uv pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu128 --force-reinstall`
 **If you use the launcher, you can do it from the built in console. In the launchers very bottom left click the  >_  button, then click "Start Dev console" and once you in just enter the above. It should start downloading some stuff, and then it should work with a RTX50XX**

extended old solution post: https://github.com/invoke-ai/InvokeAI/issues/7683#issuecomment-2717003528

**Comment by Andyx1976** [comment]
well with 5.10.1 it doesn't work that easy anymore (for me?). IT did with 5.10. 
 they changed something again, it crashes on launch again (outdated numPy stuff) . I can't be bothered right now to AGAIN try to make the easy-to-use launcher version work.  Anybody any ideas or not that problem?

**Comment by Andyx1976** [comment]
It seems using in the console
uv pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu128 --no-deps --force-reinstall
does the trick for 5.10.1.

(Install the version with the launcher, when finished click the >_ bottom left in the launcher, then "Start dev Console", than paste the command and wait til it's done).
See you in the next update when that doesn't work anymore.

**Comment by ecker00** [comment]
Will this work with driver 570.133 and cuda 12.8? Thinking maybe to wait until this is resolved, as suggestion here seems a bit daunting to configure.

```sh
$ docker run --rm --runtime=nvidia --gpus=all --publish 9090:9090 \
  --env-file ./.env \
  -v ./invokeai.yaml:/invokeai/invokeai.yaml \
  ghcr.io/invoke-ai/invokeai:5.10.1-cuda

Traceback (most recent call last):
  File "/opt/venv/bin/invokeai-web", line 10, in <module>
    sys.exit(run_app())
             ^^^^^^^^^
  File "/opt/invokeai/invokeai/app/run_app.py", line 37, in run_app
    torch_device_name = TorchDevice.get_torch_device_name()
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/invokeai/invokeai/backend/util/devices.py", line 94, in get_torch_device_name
    return torch.cuda.get_device_name(device) if device.type == "cuda" else device.type.upper()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/torch/cuda/__init__.py", line 491, in get_device_name
    return get_device_properties(device).name
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/torch/cuda/__init__.py", line 523, in get_device_properties
    _lazy_init()  # will define _get_device_properties
    ^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/torch/cuda/__init__.py", line 319, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available

```

**Comment by strayge** [comment]
For those who use docker - Dockerfile with squashed layers based on v5.11.0:
```
FROM ghcr.io/invoke-ai/invokeai:sha-7722f47-cuda AS base
RUN UV_INDEX=https://download.pytorch.org/whl/cu128 uv pip install torch==2.7.0 torchvision==0.22.0 torchaudio==2.7.0 --no-cache-dir

FROM scratch
COPY --from=base / /

ENV \
    PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    VIRTUAL_ENV=/opt/venv \
    INVOKEAI_SRC=/opt/invokeai \
    PYTHON_VERSION=3.12 \
    UV_PYTHON=3.12 \
    UV_COMPILE_BYTECODE=1 \
    UV_MANAGED_PYTHON=1 \
    UV_LINK_MODE=copy \
    UV_PROJECT_ENVIRONMENT=/opt/venv \
    UV_INDEX="https://download.pytorch.org/whl/cu124" \
    INVOKEAI_ROOT=/invokeai \
    INVOKEAI_HOST=0.0.0.0 \
    INVOKEAI_PORT=9090 \
    PATH="/opt/venv/bin:$PATH" \
    CONTAINER_UID=${CONTAINER_UID:-1000} \
    CONTAINER_GID=${CONTAINER_GID:-1000}

ARG GPU_DRIVER=cuda

WORKDIR ${INVOKEAI_SRC}

ENTRYPOINT ["/opt/invokeai/docker-entrypoint.sh"]
CMD ["invokeai-web"]
```

**Comment by jvbrt4** [comment]
Running this after installing default version is the way: uv pip install --upgrade --pre torch torchvision --index-url https://download.pytorch.org/whl/nightly/cu128

**Comment by nelno** [comment]
Note that to get the uv pip install fix to work I had to do it from UV environment started inside my invoke AI folder. Otherwise you'll end up changing your machine's default uv environment (I guess) and not the invoke one.

**Comment by psychedelicious** [comment]
Invoke supports 50xx series GPUs now, both via Launcher and manual install.

**Comment by jvbrt4** [comment]
During the update I had the same error:  × No solution found when resolving dependencies:
  ╰─▶ Because only torch<=2.6.0+cu124 is available and invokeai==6.4.0rc1
      depends on torch>=2.7.0,<2.8.dev0, we can conclude that
      invokeai==6.4.0rc1 cannot be used.
      And because you require invokeai==6.4.0rc1, we can conclude that your
      requirements are unsatisfiable.
      hint: `torch` was requested with a pre-release marker (e.g.,
      torch>=2.7.0,<2.8.dev0), but pre-releases weren't enabled (try:
      `--prerelease=allow`)
      hint: `torch` was found on https://download.pytorch.org/whl/cu124,
      but not at the requested version (torch>=2.7.0,<2.8.dev0). A
      compatible version may be available on a subsequent index (e.g.,
      https://pypi.org/simple). By default, uv will only consider versions
      that are published on the first index that contains a given package, to
      avoid dependency confusion attacks. If all indexes are equally trusted,
      use `--index-strategy unsafe-best-match` to consider all versions from
      all indexes, regardless of the order in which they were defined.
Failed to install invokeai python package: Process exited with code 1

**Comment by strayge** [comment]
Can confirm that new docker image `v6.4.0rc1-cuda` build with CUDA 12.8 (`torch 2.7.1+cu128`).

Thank you.

**Comment by psychedelicious** [comment]
@jvbrt4 Make sure you are using the latest launcher.
