### ISSUE TITLE
Workaround for low memory and full precision cards

### ISSUE THREAD

**Issue by ArDiouscuros** [invoke-ai/InvokeAI#775]
**Problem**
Even with current development branch I am not always able to generate 512x512 images. Crash happens after sampling - so after a long wait  I get a error instead of picture. I am on limited hardware - GTX 1660 Ti with 6GB, so I must use full precision and memory is full.

**Solution**
Move sampler part of model off gpu before doing conversion to image

**Additional context**
```
* Initialization done! Awaiting your command (-h for help, 'q' to quit)
dream> squirell mecha knight
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [01:53<00:00,  2.28s/it]
Generating:   0%|                                                                                                    | 0/1 [01:56<?, ?it/s]
Traceback (most recent call last):
  File "g:\programs\sdai\stablediffusionmanual\repo\lstein\stable-diffusion\ldm\generate.py", line 342, in prompt2image
    results = generator.generate(
  File "g:\programs\sdai\stablediffusionmanual\repo\lstein\stable-diffusion\ldm\dream\generator\base.py", line 70, in generate
    image = make_image(x_T)
  File "G:\Programs\SDAI\StableDiffusionManual\conda\envs\ldm\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "g:\programs\sdai\stablediffusionmanual\repo\lstein\stable-diffusion\ldm\dream\generator\txt2img.py", line 42, in make_image
    return self.sample_to_image(samples)
  File "g:\programs\sdai\stablediffusionmanual\repo\lstein\stable-diffusion\ldm\dream\generator\base.py", line 82, in sample_to_image
    x_samples = self.model.decode_first_stage(samples)
  File "G:\Programs\SDAI\StableDiffusionManual\conda\envs\ldm\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "g:\programs\sdai\stablediffusionmanual\repo\lstein\stable-diffusion\ldm\models\diffusion\ddpm.py", line 1117, in decode_first_stage
    return self.first_stage_model.decode(z)
  File "g:\programs\sdai\stablediffusionmanual\repo\lstein\stable-diffusion\ldm\models\autoencoder.py", line 421, in decode
    dec = self.decoder(z)
  File "G:\Programs\SDAI\StableDiffusionManual\conda\envs\ldm\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "g:\programs\sdai\stablediffusionmanual\repo\lstein\stable-diffusion\ldm\modules\diffusionmodules\model.py", line 603, in forward
    h = self.up[i_level].block[i_block](h, temb)
  File "G:\Programs\SDAI\StableDiffusionManual\conda\envs\ldm\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "g:\programs\sdai\stablediffusionmanual\repo\lstein\stable-diffusion\ldm\modules\diffusionmodules\model.py", line 125, in forward
    h = nonlinearity(h)
  File "g:\programs\sdai\stablediffusionmanual\repo\lstein\stable-diffusion\ldm\modules\diffusionmodules\model.py", line 37, in nonlinearity

    return x*torch.sigmoid(x)
RuntimeError: CUDA out of memory. Tried to allocate 256.00 MiB (GPU 0; 6.00 GiB total capacity; 4.82 GiB already allocated; 50.29 MiB free;
4.93 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See
documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

>> Could not generate image.
>> Usage stats:
>>   0 image(s) generated in 117.05s
>>   Max VRAM used for this generation: 5.17G. Current VRAM utilization: 4.36G
>>   Max VRAM used since script start:  5.17G
Outputs:
```

**Comment by kriptolix** [comment]
This is weird, I have a 1060 6g and I have no problem rendering resolutions even above 512x512 (I tend to always use 704x512).

There's only one exception, the first time I got an "out of memory" message was using the new WebUI, which made me go back to the command line. Any other case doesn't even use 4g of Vram.

**Comment by ArDiouscuros** [comment]
> I have a 1060 6g and I have no problem rendering resolutions even above
@kriptolix 
You are right, with 1060 and 6Gb you could actually use float16 / hall precision mode and enjoy high resolutions.
On GTX 16xx there is a bug, such as in half precision mode CUDA compute some values as NaN and images produced are flat green squares. 
Currently I am and other 16xx users forced to use full precision, and it is using around 4.5 GB VRAM just to load model.

**Comment by ArDiouscuros** [comment]
It is working now with latest development branch version and free gpu mem option.
