### ISSUE TITLE
Nvidia RTX 5060 TI compatibility

### ISSUE THREAD

**Issue by OldUncleMike** [invoke-ai/InvokeAI#7934]
### Is there an existing issue for this problem?

- [x] I have searched the existing issues

### Operating system

Windows

### GPU vendor

Nvidia (CUDA)

### GPU model

RTX 5060 TI 

### GPU VRAM

16GB

### Version number

5.10.0

### Browser

Chrome

### Python dependencies

{
    "version": "5.10.0", 
    "dependencies": {
        "accelerate"  : "1.6.0"       , 
        "compel"      : "2.0.2"       , 
        "cuda"        : "12.4"        , 
        "diffusers"   : "0.33.0"      , 
        "numpy"       : "1.26.3"      , 
        "opencv"      : "4.9.0.80"    , 
        "onnx"        : "1.16.1"      , 
        "pillow"      : "11.0.0"      , 
        "python"      : "3.11.10"     , 
        "torch"       : "2.6.0+cu124" , 
        "torchvision" : "0.21.0+cu124", 
        "transformers": "4.51.3"      , 
        "xformers"    : null            
    }, 
    "config": {
        "schema_version": "4.0.2", 
        "legacy_models_yaml_path": null, 
        "host": "127.0.0.1", 
        "port": 9090, 
        "allow_origins": [], 
        "allow_credentials": true, 
        "allow_methods": ["*"], 
        "allow_headers": ["*"], 
        "ssl_certfile": null, 
        "ssl_keyfile": null, 
        "log_tokenization": false, 
        "patchmatch": true, 
        "models_dir": "models", 
        "convert_cache_dir": "models\\.convert_cache", 
        "download_cache_dir": "models\\.download_cache", 
        "legacy_conf_dir": "configs", 
        "db_dir": "databases", 
        "outputs_dir": "outputs", 
        "custom_nodes_dir": "nodes", 
        "style_presets_dir": "style_presets", 
        "workflow_thumbnails_dir": "workflow_thumbnails", 
        "log_handlers": ["console"], 
        "log_format": "color", 
        "log_level": "info", 
        "log_sql": false, 
        "log_level_network": "warning", 
        "use_memory_db": false, 
        "dev_reload": false, 
        "profile_graphs": false, 
        "profile_prefix": null, 
        "profiles_dir": "profiles", 
        "max_cache_ram_gb": null, 
        "max_cache_vram_gb": null, 
        "log_memory_usage": false, 
        "device_working_mem_gb": 3, 
        "enable_partial_loading": true, 
        "keep_ram_copy_of_weights": true, 
        "ram": null, 
        "vram": null, 
        "lazy_offload": true, 
        "pytorch_cuda_alloc_conf": "backend:cudaMallocAsync", 
        "device": "auto", 
        "precision": "auto", 
        "sequential_guidance": false, 
        "attention_type": "auto", 
        "attention_slice_size": "auto", 
        "force_tiled_decode": false, 
        "pil_compress_level": 1, 
        "max_queue_size": 10000, 
        "clear_queue_on_startup": false, 
        "allow_nodes": null, 
        "deny_nodes": null, 
        "node_cache_size": 512, 
        "hashing_algorithm": "blake3_single", 
        "remote_api_tokens": null, 
        "scan_models_on_startup": false
    }, 
    "set_config_fields": ["legacy_models_yaml_path", "enable_partial_loading", "pytorch_cuda_alloc_conf"]
}

### What happened

CUDA sm120 used by RTX 5060TI is not supported by PyTorch. Error:
NVIDIA GeForce RTX 5060 Ti with CUDA capability sm_120 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_50 sm_60 sm_61 sm_70 sm_75 sm_80 sm_86 sm_90.
If you want to use the NVIDIA GeForce RTX 5060 Ti GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

...

RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
...

### What you expected to happen

RTX 5060 TI to be supported, soon, please.

### How to reproduce the problem

Run the community version with RTX 5060 TI

### Additional context

Just purchased and installed new RTX 5060 TI from working RTX 2060 (6GB).
If I can help let me know what to do.
I am on Discord, though I tend not to use it as much as I should
Thanks

### Discord username

unclemike2997

**Comment by Andyx1976** [comment]
> When PyTorch becomes stable I'm sure this will be included in the Invoke distribution

I wonder, how many month after everybody else that will be. It's about 3 months now and counting.

**Comment by fan9704** [comment]
I use RTX5060TI too I met same problem

**Comment by Andyx1976** [comment]
well with 5.10.1 it doesn't work that easy anymore. IT did with 5.10. 
 they changed something again, it crashes on launch again (outdated numPy stuff) . I can't be bothered right now to AGAIN try to make the easy-to-use launcher version work.
Anybody any ideas or not that problem?

**Comment by OldUncleMike** [comment]
The thing to watch out for is when you want to update Invoke.
For me I had to use the Repair Option (tiny check box, bottom left Invoke Community Edition, before you hit the update button). Then re-apply the fix.
Hope its stable enough to incorporate soon.

**Comment by mwenz27** [comment]
> Found a workaround. Thanks to **Outremer** on Discord, Thanks. First ,make sure you are using a recent version of Invoke Community Edition, 1.2.1 does not work, 1.5.0 does work.
> 
> > try this - after opening the invoke app (reset your invoke install) - click on manage, click next, select the latest stable version (V5.10.0 at the moment), click next, select the nvidia 30x and above option, click next, click on the repair mode checkbox and click install.
> > after this completes, click on the Dev console button in the lower left hand corner of the window and click on "start dev console". run the following command
> > uv pip install --pre torch torchvision torchaudio  --index-url https://download.pytorch.org/whl/nightly/cu128 --upgrade --force-reinstall
> 
> When PyTorch becomes stable I'm sure this will be included in the Invoke distribution

I followed the instructions - got a new error code

_''module that was compiled using NumPy 1.x cannot be run in NumPy 2.1.2 as it may crash. To support both 1.x and 2.x versions of NumPy, modules must be compiled with NumPy 2.0. Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.''_

I am able to get it to work when downgrading numpy with this command

`uv pip install numpy<2.0`

**Comment by Andyx1976** [comment]
> The thing to watch out for is when you want to update Invoke. For me I had to use the Repair Option (tiny check box, bottom left Invoke Community Edition, before you hit the update button). Then re-apply the fix. Hope its stable enough to incorporate soon.

i have the official response that they will only do that when Pytorch 128 becomes officially stable. Til then it will be interesting because with the 5060 it's not just "a few rich people who can afford a 5090" anymore, that you can just ignore..

**Comment by mobius29er** [comment]
> ### Currently working solution for: 5.10.1 It seems using in the console:
> `uv pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu128 --no-deps --force-reinstall` does the trick for 5.10.1.
> 
> ### Howto:
> Install the version with the launcher, Apparently (one post below) you have to check "repair" as well during installing. When it's finished click the `>_` , bottom left in the launcher, then click "Start dev Console", then paste the command above (exactly) and wait til it's done. It should start downloading about 3GB of stuff)). Post exactly that, it needs --no-deps or it will crash on launch.
> 
> See you in the next update when that doesn't work anymore. **Actually, if you have it working you may wanna skip smaller updates, it's not worth the trouble finding a new fix (Every. single. time.)** Thankfully at least the bitsandbytes version the launcher installs is now up to date and fully works out of the (launcher)box with Pytorch128... Baby steps.

this works as a workaround thank you.

**Comment by fan9704** [comment]
Right now pytorch 2.7 cu128 was stable version everyone can try to install it for rtx 50xx

**Comment by ecker00** [comment]
Related: #7683

**Comment by fan9704** [comment]
> Right now pytorch 2.7 cu128 was stable version everyone can try to install it for rtx 50xx

Try It 

```shell
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu128
```

Ref: [Pytorch Get-Started](https://pytorch.org/get-started/locally/)

**Comment by ZhuShaoQiang** [comment]
> > Right now pytorch 2.7 cu128 was stable version everyone can try to install it for rtx 50xx
> 
> Try It
> 
> pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu128
> Ref: [Pytorch Get-Started](https://pytorch.org/get-started/locally/)

It doesn't work:
```bash
>>> pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu128
Looking in indexes: https://download.pytorch.org/whl/cu128
ERROR: Could not find a version that satisfies the requirement torch (from versions: none)
ERROR: No matching distribution found for torch
```
I am using Ubuntu 18.04, x86_64, python=3.12.9.

**Comment by fan9704** [comment]
> > > Right now pytorch 2.7 cu128 was stable version everyone can try to install it for rtx 50xx
> > 
> > 
> > Try It
> > pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu128
> > Ref: [Pytorch Get-Started](https://pytorch.org/get-started/locally/)
> 
> and, even if I try to install preview version: ![Image](https://github.com/user-attachments/assets/67c4333e-589c-4d60-b490-93ddd85beea8) It doesn't work too:
> 
> >>> pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu128
> Looking in indexes: https://download.pytorch.org/whl/nightly/cu128
> ERROR: Could not find a version that satisfies the requirement torch (from versions: none)
> ERROR: No matching distribution found for torch

How about this because right now it didn,t need preview version


```shell
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu128
```

**Comment by fan9704** [comment]
> > > Right now pytorch 2.7 cu128 was stable version everyone can try to install it for rtx 50xx
> > 
> > 
> > Try It
> > pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu128
> > Ref: [Pytorch Get-Started](https://pytorch.org/get-started/locally/)
> 
> It doesn't work:
> 
> >>> pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu128
> Looking in indexes: https://download.pytorch.org/whl/cu128
> ERROR: Could not find a version that satisfies the requirement torch (from versions: none)
> ERROR: No matching distribution found for torch
> I am using Ubuntu 18.04, x86_64, python=3.12.9.

Maybe your OS is too old(not sure) becuase CUDA Toolkit 12.8 Only support 20.04 22.04 24.04

**Comment by OldUncleMike** [comment]
Try updating to 5.12 or later which installs pytorch 2.7.0 using cu128. This should work for most people with RTX50XX cards

**Comment by RobertHRUBY** [comment]
> > > Right now pytorch 2.7 cu128 was stable version everyone can try to install it for rtx 50xx
> > 
> > 
> > Try It
> > pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu128
> > Ref: [Pytorch Get-Started](https://pytorch.org/get-started/locally/)
> 
> and, even if I try to install preview version: ![Image](https://github.com/user-attachments/assets/67c4333e-589c-4d60-b490-93ddd85beea8) It doesn't work too:
> 
> >>> pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu128
> Looking in indexes: https://download.pytorch.org/whl/nightly/cu128
> ERROR: Could not find a version that satisfies the requirement torch (from versions: none)
> ERROR: No matching distribution found for torch

Nvidia latest driver: https://www.nvidia.com/en-us/drivers/details/245669/
in combination with Ubuntu 20.04 work for me. 
note: Cuda works, no problem with training.

**Comment by psychedelicious** [comment]
Invoke supports 50xx series GPUs now, both via Launcher and manual install.

**Comment by zaqwes8811** [comment]
`docker build -t rtx5060-sm120-pytorch -f Dockerfile.sm120 .`
