### ISSUE TITLE
[bug]: AMD doesn't use CUDA

### ISSUE THREAD

**Issue by webmaster-exit-1** [invoke-ai/InvokeAI#8084]
### Is there an existing issue for this problem?

- [x] I have searched the existing issues

### Operating system

Linux

### GPU vendor

AMD (ROCm)

### GPU model

RX 79000 XTX

### GPU VRAM

24

### Version number

v5.13.0rc3

### Browser

chrome

### What happened

🚨 CUDA VERSION MISMATCH 🚨
Requested CUDA version:          6.3
Detected PyTorch CUDA version:   6.3
Available pre-compiled versions: 
  - 11.8
  - 12.0
  - 12.1
  - 12.2
  - 12.3
  - 12.4
  - 12.5
  - 12.6
  - 12.8
This means:
The version you're trying to use is NOT distributed with this package
Attempted to use bitsandbytes native library functionality but it's not available.
This typically happens when:
1. bitsandbytes doesn't ship with a pre-compiled binary for your CUDA version
2. The library wasn't compiled properly during installation from source
To make bitsandbytes work, the compiled library version MUST exactly match the linked CUDA version.
If your CUDA version doesn't have a pre-compiled binary, you MUST compile from source.
You have two options:
1. COMPILE FROM SOURCE (required if no binary exists):
   https://huggingface.co/docs/bitsandbytes/main/en/installation#cuda-compile
2. Use BNB_CUDA_VERSION to specify a DIFFERENT CUDA version from the detected one, which is installed on your machine and matching an available pre-compiled version listed above
Original error: Configured CUDA binary not found at /run/media/mrgfy/ALPHA/Invokeai/.venv/lib/python3.12/site-packages/bitsandbytes/libbitsandbytes_rocm63.so
🔍 Run this command for detailed diagnostics:
python -m bitsandbytes
If you've tried everything and still have issues:
1. Include ALL version info (operating system, bitsandbytes, pytorch, cuda, python)
2. Describe what you've tried in detail
3. Open an issue with this information:
   https://github.com/bitsandbytes-foundation/bitsandbytes/issues

ROCM and AMD does not use CUDA or BitsandBytes!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

This should NOT be a factor when using AMD hardware!!!!!!!!
Unacceptable!!!!

### What you expected to happen

For it to work.

**Comment by lovedayb** [comment]
I think you need to read the documentation first. This is an AMD issue, not an Invoke-AI problem. Once the ROCm support improves on Windows then maybe this will be addressed, or if support for ZLUDA is implemented. 
How is this unacceptable? Have you provided any support to the developers?

**Comment by webmaster-exit-1** [comment]
No, I fixed it. My version of Invoke now reads my amd gpu with Zero cuda or bitsandbytes errors. Good luck fixing it. Have an AI help you like I did. The main guy in your discord is a jerk so I won't be sharing how I fixed it. Unacceptable = Since the installer gives an AMD option, your software should therefore work on AMD, which it does not unless you make the correct edits, such as I have.
